import type { WorkflowStateSnapshot } from "../../src/lib/types";

type ProjectBlackboardFixture = NonNullable<WorkflowStateSnapshot["project_blackboards"]>[number];

export function projectBlackboardFixture(projectRoot: string): ProjectBlackboardFixture {
  return {
    project_id: "project:offline-fixture-projects-codex-workbench",
    project_root: projectRoot,
    workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
    entries: [
      {
        entry_id: "blackboard:offline:report:001",
        project_id: "project:offline-fixture-projects-codex-workbench",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        work_item_id: null,
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        kind: "subagent_report",
        title: "子智能体汇报 / codex-dev",
        summary: "离线桩结果：已接收任务，没有执行真实 Codex 会话。",
        status: "candidate",
        source_status: "reported_not_completed",
        source_refs: [{ source_kind: "subagent_report", source_id: "report:dispatch:offline:001", label: "子智能体汇报" }],
        created_at: null,
        promotion_decision: {
          decision_id: "promotion:blackboard:offline:report:001",
          status: "candidate_pending_control_core",
          target_kind: "workflow_fact",
          decided_by_role: null,
          decided_at: null,
          reason: "必须经控制核心确认后才能升级为正式事实。",
          audit_refs: [],
          warnings: ["not_promoted_without_control_core_confirmation"],
        },
        warnings: ["blackboard_entry_is_candidate_only"],
      },
      {
        entry_id: "blackboard:offline:risk:001",
        project_id: "project:offline-fixture-projects-codex-workbench",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        work_item_id: null,
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        kind: "risk",
        title: "方向风险候选",
        summary: "direction_risk_fixture",
        status: "candidate",
        source_status: "reported_not_completed",
        source_refs: [{ source_kind: "subagent_report", source_id: "report:dispatch:offline:001", label: "风险来源" }],
        created_at: null,
        promotion_decision: {
          decision_id: "promotion:blackboard:offline:risk:001",
          status: "candidate_pending_control_core",
          target_kind: "workflow_risk",
          decided_by_role: null,
          decided_at: null,
          reason: "风险只作为黑板候选，不直接推进状态。",
          audit_refs: [],
          warnings: ["not_promoted_without_control_core_confirmation"],
        },
        warnings: ["risk_candidate_not_workflow_state_transition"],
      },
      {
        entry_id: "blackboard:offline:permission:001",
        project_id: "project:offline-fixture-projects-codex-workbench",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        work_item_id: "work-item:offline:001",
        workflow_node_id: null,
        kind: "permission_request",
        title: "权限请求 / write_workflow_state",
        summary: "需要用户确认是否允许写协议字段。",
        status: "candidate",
        source_status: "pending",
        source_refs: [{ source_kind: "permission_request", source_id: "permission:offline:001", label: "权限请求" }],
        created_at: "2026-05-30T00:00:00Z",
        promotion_decision: {
          decision_id: "promotion:blackboard:offline:permission:001",
          status: "candidate_pending_control_core",
          target_kind: "permission_decision",
          decided_by_role: null,
          decided_at: null,
          reason: "权限请求不能由黑板直接批准或推进状态。",
          audit_refs: [],
          warnings: ["not_promoted_without_control_core_confirmation"],
        },
        warnings: ["permission_request_requires_control_core_decision"],
      },
      {
        entry_id: "blackboard:offline:tool:001",
        project_id: "project:offline-fixture-projects-codex-workbench",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        work_item_id: "work-item:offline:001",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        kind: "tool_summary",
        title: "工具摘要候选",
        summary: "工具调用只保留摘要和引用，不保留完整输出。",
        status: "candidate",
        source_status: null,
        source_refs: [{ source_kind: "tool_call", source_id: "tool-call:offline:001", label: "工具调用引用" }],
        created_at: "2026-05-30T00:02:00Z",
        promotion_decision: {
          decision_id: "promotion:blackboard:offline:tool:001",
          status: "candidate_pending_control_core",
          target_kind: "audit_event",
          decided_by_role: null,
          decided_at: null,
          reason: "工具摘要不会把工具全文直接升级为审计事件或事实。",
          audit_refs: [],
          warnings: ["not_promoted_without_control_core_confirmation"],
        },
        warnings: ["tool_summary_is_not_full_tool_output"],
      },
      {
        entry_id: "blackboard:offline:memory:001",
        project_id: "project:offline-fixture-projects-codex-workbench",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        work_item_id: null,
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:director",
        kind: "memory_candidate",
        title: "记忆候选",
        summary: "memory:candidate:offline:001 只是候选，不写正式记忆。",
        status: "candidate",
        source_status: "fresh_task_package",
        source_refs: [{ source_kind: "memory_candidate", source_id: "memory:candidate:offline:001", label: "记忆候选" }],
        created_at: null,
        promotion_decision: {
          decision_id: "promotion:blackboard:offline:memory:001",
          status: "candidate_pending_control_core",
          target_kind: "formal_memory",
          decided_by_role: null,
          decided_at: null,
          reason: "记忆候选不能由黑板直接写正式记忆。",
          audit_refs: [],
          warnings: ["not_promoted_without_control_core_confirmation"],
        },
        warnings: ["memory_candidate_not_formal_memory"],
      },
      {
        entry_id: "blackboard:offline:knowledge:001",
        project_id: "project:offline-fixture-projects-codex-workbench",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        work_item_id: null,
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:director",
        kind: "knowledge_ref",
        title: "知识引用",
        summary: "knowledge:offline:001 是资料来源，不会被当作记忆写入。",
        status: "candidate",
        source_status: "fresh_task_package",
        source_refs: [{ source_kind: "knowledge_ref", source_id: "knowledge:offline:001", label: "知识引用" }],
        created_at: null,
        promotion_decision: {
          decision_id: "promotion:blackboard:offline:knowledge:001",
          status: "candidate_pending_control_core",
          target_kind: "knowledge_reference",
          decided_by_role: null,
          decided_at: null,
          reason: "知识引用不能被黑板直接升级为正式记忆。",
          audit_refs: [],
          warnings: ["not_promoted_without_control_core_confirmation"],
        },
        warnings: ["knowledge_ref_is_not_memory"],
      },
    ],
    warnings: [
      "project_blackboard_is_read_model_only",
      "blackboard_promotion_requires_control_core_confirmation",
    ],
  };
}
