import type {
  FormalMemoryStoreV1,
  MemoryLintStoreV1,
  TaskMemoryPacketBuildOutput,
} from "../../src/lib/types";

interface CandidateMemoryLifecycleFixtureInput {
  workflowProjectId: string;
  workflowId: string;
}

export function candidateMemoryLifecycleFixtures(input: CandidateMemoryLifecycleFixtureInput) {
  const { workflowProjectId, workflowId } = input;

  const formalMemoryStore: FormalMemoryStoreV1 = {
    store_version: "formal_memory_store.v1",
    project_id: "project:offline",
    workflow_id: "workflow:offline:default",
    revision: 4,
    records: [
      {
        memory_id: "mem:formal:offline:001",
        schema_version: "memory_governance.v1",
        record_version: 1,
        scope: {
          scope_id: "scope:project:offline",
          scope_type: "project",
          project_id: "project:offline",
          workflow_id: "workflow:offline:default",
          role_ids: [],
          document_refs: [],
          model_export_policy: "local_only",
          valid_from: "2026-06-03T00:00:00Z",
        },
        memory_type: "project_memory",
        claim: "正式记忆创建必须写 version 和 audit。",
        body: "M1 只验证正式记忆骨架，不做任务包注入。",
        source_refs: [
          {
            source_ref_id: "source:offline:formal:001",
            source_type: "stage_report",
            source_id: "stage:offline",
            source_title: "离线正式记忆测试",
            captured_at: "2026-06-03T00:00:00Z",
            authority_level: "evidence",
            sensitive_level: "project",
          },
        ],
        status: "memory_active",
        supersedes_memory_id: null,
        superseded_by_memory_id: null,
        conflict_refs: [],
        audit_refs: [],
        created_at: "2026-06-03T00:00:00Z",
        updated_at: "2026-06-03T00:00:00Z",
      },
    ],
    versions: [
      {
        version_id: "memver:formal:offline:001",
        memory_id: "mem:formal:offline:001",
        version_number: 1,
        change_type: "created",
        change_summary: "创建正式记忆第一版。",
        record_snapshot: {
          memory_id: "mem:formal:offline:001",
          schema_version: "memory_governance.v1",
          record_version: 1,
          scope: {
            scope_id: "scope:project:offline",
            scope_type: "project",
            project_id: "project:offline",
            workflow_id: "workflow:offline:default",
            role_ids: [],
            document_refs: [],
            model_export_policy: "local_only",
            valid_from: "2026-06-03T00:00:00Z",
          },
          memory_type: "project_memory",
          claim: "正式记忆创建必须写 version 和 audit。",
          body: "M1 只验证正式记忆骨架，不做任务包注入。",
          source_refs: [],
          status: "memory_active",
          supersedes_memory_id: null,
          superseded_by_memory_id: null,
          conflict_refs: [],
          audit_refs: [],
          created_at: "2026-06-03T00:00:00Z",
          updated_at: "2026-06-03T00:00:00Z",
        },
        source_refs: [],
        changed_by_role: "project_director",
        reviewed_by: null,
        created_at: "2026-06-03T00:00:00Z",
      },
    ],
    audit_events: [
      {
        audit_event_id: "audit:formal:offline:001",
        event_type: "memory_record_created",
        actor_id: "project-director-offline",
        actor_role: "project_director",
        project_id: "project:offline",
        workflow_id: "workflow:offline:default",
        session_id: null,
        target_kind: "memory_record",
        target_id: "mem:formal:offline:001",
        before_state: null,
        after_state: "memory_active",
        reason: "离线正式记忆测试",
        source_refs: [],
        status: "succeeded",
        created_at: "2026-06-03T00:00:00Z",
      },
    ],
    updated_at: "2026-06-03T00:00:00Z",
    warnings: [],
  };

  const adoptedFormalMemoryStore: FormalMemoryStoreV1 = {
    store_version: "formal_memory_store.v1",
    project_id: "project:offline",
    workflow_id: "workflow:offline:default",
    revision: 5,
    records: [],
    versions: [],
    audit_events: [
      {
        audit_event_id: "audit:formal:offline:002",
        event_type: "memory_candidate_adopted_to_formal_memory",
        actor_id: "project-director-offline",
        actor_role: "project_director",
        project_id: "project:offline",
        workflow_id: "workflow:offline:default",
        session_id: null,
        target_kind: "memory_record",
        target_id: "mem:formal:offline:002",
        before_state: null,
        after_state: "memory_active",
        reason: "项目主管采纳低风险本项目记忆候选。",
        source_refs: [],
        status: "succeeded",
        created_at: "2026-06-03T00:00:02Z",
      },
    ],
    updated_at: "2026-06-03T00:00:02Z",
    warnings: [],
  };

  const memoryLintStore: MemoryLintStoreV1 = {
    store_version: "memory_lint_store.v1",
    project_id: workflowProjectId,
    workflow_id: workflowId,
    revision: 2,
    findings: [
      {
        finding_id: "memlint:v1:offline:blocking",
        schema_version: "memory_governance.v1",
        finding_type: "source_permission_revoked",
        severity: "blocking",
        status: "open",
        source_kind: "memory_record",
        source_id: "mem:formal:offline:revoked",
        target_memory_id: "mem:formal:offline:revoked",
        target_candidate_key: null,
        scope_type: "project",
        memory_type: "project_memory",
        claim: "撤回来源不能进入任务记忆包。",
        summary: "来源权限撤回产生 open blocking finding。",
        recommended_action: "exclude_from_task_packet",
        evidence_refs: [],
        audit_event_id: null,
        created_at: "2026-06-04T02:00:00Z",
        updated_at: "2026-06-04T02:00:00Z",
      },
      {
        finding_id: "memlint:v1:offline:review",
        schema_version: "memory_governance.v1",
        finding_type: "duplicate_claim",
        severity: "needs_review",
        status: "open",
        source_kind: "memory_record",
        source_id: "mem:formal:offline:duplicate",
        target_memory_id: "mem:formal:offline:duplicate",
        target_candidate_key: null,
        scope_type: "project",
        memory_type: "project_memory",
        claim: "重复 claim 需要人工复核。",
        summary: "重复 claim 只生成 needs_review finding。",
        recommended_action: "review_and_deprecate",
        evidence_refs: [],
        audit_event_id: null,
        created_at: "2026-06-04T02:00:01Z",
        updated_at: "2026-06-04T02:00:01Z",
      },
      {
        finding_id: "memlint:v1:offline:resolved",
        schema_version: "memory_governance.v1",
        finding_type: "candidate_conflicts_with_active_memory",
        severity: "blocking",
        status: "resolved",
        source_kind: "memory_candidate",
        source_id: "memcand:v1:offline-resolved",
        target_memory_id: "mem:formal:offline:old",
        target_candidate_key: "memcand:v1:offline-resolved",
        scope_type: "project",
        memory_type: "project_memory",
        claim: "已解决 finding 不应计入 open blocking。",
        summary: "resolved blocking finding 不计入 open blocking 摘要。",
        recommended_action: "block_adoption",
        evidence_refs: [],
        audit_event_id: null,
        created_at: "2026-06-04T02:00:02Z",
        updated_at: "2026-06-04T02:00:02Z",
      },
    ],
    runs: [
      {
        run_id: "memlint-run:v1:offline",
        lint_intent: "candidate_adoption_guard",
        actor_id: "project-director-offline",
        actor_role: "project_director",
        finding_ids: ["memlint:v1:offline:blocking"],
        blocking_count: 1,
        status: "blocked",
        reason: "candidate_adoption_guard blocked by 1 blocking finding",
        created_at: "2026-06-04T02:00:03Z",
      },
    ],
    updated_at: "2026-06-04T02:00:03Z",
    warnings: ["memory_lint_findings_only_no_formal_memory_mutation"],
  };

  const taskMemoryPacketPreview: TaskMemoryPacketBuildOutput = {
    preview: {
      packet_id: "task-memory-packet-preview:v1:offline",
      schema_version: "task_memory_packet.v1",
      project_id: workflowProjectId,
      workflow_id: workflowId,
      task_id: "work-item:offline:001",
      role_id: "codex-dev",
      retrieval_intent: "worker_task",
      included_memories: [
        {
          memory_id: "mem:formal:offline:included",
          memory_type: "project_memory",
          scope_type: "project",
          claim: "接口验收必须保留控制核心边界。",
          body: "活跃正式记忆可以进入任务记忆包预览。",
          source_refs: [],
          retrieval_reason: "active formal memory matched task goal by 接口；scope=project",
          estimated_tokens: 28,
          model_export_policy: "local_only",
        },
      ],
      excluded_items: [
        {
          source_kind: "memory_candidate",
          source_id: "memcand:v1:offline-packet",
          claim: "候选还没有受控采纳。",
          reason: "candidate_unconfirmed",
          detail: "记忆候选不是正式记忆；不会进入任务记忆包入选列表",
        },
        {
          source_kind: "observation",
          source_id: "obs:v1:offline-packet",
          claim: "观察只作为待审查材料。",
          reason: "observation_not_formal_memory",
          detail: "观察不是正式记忆；不会进入任务记忆包入选列表",
        },
      ],
      review_materials: [
        {
          source_kind: "memory_candidate",
          source_id: "memcand:v1:offline-packet",
          title: "候选还没有受控采纳。",
          reason: "candidate_unconfirmed",
        },
        {
          source_kind: "observation",
          source_id: "obs:v1:offline-packet",
          title: "观察只作为待审查材料。",
          reason: "observation_not_formal_memory",
        },
      ],
      estimated_tokens: 28,
      max_estimated_tokens: 8000,
      generated_at: "2026-06-04T01:00:00Z",
      warnings: [
        "preview_only_not_injected",
        "worker_has_not_received_memory_packet",
        "candidate_and_observation_review_materials_only",
      ],
    },
    formal_store_revision: 4,
    candidate_store_revision: 3,
    observation_store_revision: 2,
    lint_store_revision: 5,
    warnings: ["preview_only_not_injected"],
  };

  return {
    formalMemoryStore,
    adoptedFormalMemoryStore,
    memoryLintStore,
    taskMemoryPacketPreview,
  };
}
