export const projectRuntimeTranscriptRoleTextFixtures = {
  projectCanvasBoundaryExpectedTexts: [
    "实验 / 模板画布",
    "experiment / template / canvas library",
    "不会写项目事实",
    "不会写正式记忆",
    "不会写项目工作流状态",
    "不是项目 workflow 事实源",
    "MCP canvas run 非默认项目工作流",
    "项目工作流画布",
    "工作流状态派生读模型",
    "方案授权 / 控制核心 / 权限 / 审计",
    "React Flow 仅负责渲染",
    "实验画布不会写入本项目事实",
  ],
  projectCanvasDetailLayers: ["user_summary", "project_director", "technical_details"],
  projectCanvasDetailKinds: [
    "summary",
    "task_package",
    "memory_packet",
    "session_binding",
    "dispatch",
    "readback",
    "permission_requests",
    "blackboard_entries",
    "completion_gate",
    "audit_refs",
  ],
  projectCanvasUserSummaryLabels: ["当前节点", "当前状态", "为什么停下", "谁能处理", "下一步"],
  projectCanvasStateExampleIds: [
    "empty",
    "four_roles",
    "prepared",
    "running",
    "needs_review",
    "waiting_permission",
    "blocked",
    "failed",
    "timed_out",
    "readback_unavailable",
    "reviewing",
    "accepted",
  ],
  runtimeLogManagementExpectedTexts: [
    "管理",
    "管理摘要",
    "原始材料仍在开发者区或详情中查看",
    "健康 / 诊断边界",
    "degraded_readonly",
    "工作流事实层",
    "读回不可用不是 0 条结果",
    "不自动修复 store",
    "诊断 bundle",
    "日志 / 审计边界",
    "运行日志与审计事件不能互相替代",
    "应用会话",
    "工作流运行",
    "派发尝试",
    "读回",
    "权限等待",
    "诊断事件",
    "审计引用 1",
  ],
  runtimeLogSensitiveForbiddenTexts: [
    "sk-test-secret",
    "raw provider credential",
    "完整 transcript",
    "full transcript",
    "OAuth",
    "auth.json",
    ".env",
    "keychain",
    "provider credential",
  ],
  sessionCenterExpectedTexts: [
    "搜索会话",
    "可读取",
    "缺回放记录",
    "已归档",
    "路径被安全边界拒绝",
    "rollout_outside_allowed_dirs",
  ],
  sessionCenterExpectedClasses: [
    "agent-session-shell",
    "agent-session-list",
    "agent-transcript-panel",
    "session-state-filter",
  ],
  transcriptExpectedTexts: [
    "已收纳较早 3 条消息",
    "展开全部",
    "展开",
    "开发者详情：过程事件",
    "复制",
    "const ok = true;",
  ],
  offlineRoleMissingFieldLabels: ["目标", "执行目录", "允许读取", "允许写入", "禁止事项", "验收标准", "超时", "回传要求"],
  offlineRoleDispatchDialogExpectedTexts: [
    "离线派发给开发线",
    "目标角色",
    "开发线",
    "任务名",
    "README 极小修改验证",
    "必须回传",
    "验证结果",
    "不启动 Codex",
    "不执行 codex exec resume",
    "不写 /Users/yoyi/.codex",
    "工作流状态",
  ],
  offlineRolePanelExpectedTexts: [
    "Codex 角色编排",
    "总指导派发闭环",
    "总指导",
    "开发线",
    "验证线",
    "回收线",
    "总指导回复里的派发块",
    "写入离线派发",
    "写入角色回传",
    "写入总指导回收",
    "账本锚点",
    "已有任务草稿",
    "派发预览",
    "角色回传",
    "回传总指导",
    "不启动 Codex",
    "不写 /Users/yoyi/.codex",
    "离线编排账本",
    "预览来自默认示例",
  ],
} as const;
