import type {
  FormalMemoryStoreV1,
  MemoryCandidateStoreV1,
  MemoryCaptureStoreV1,
  ObservationStoreV1,
} from "../../src/lib/types";

const workflowProjectId = "project:offline-fixture-projects-codex-workbench";
const workflowId = "workflow:offline-fixture-projects-codex-workbench:default";

export function memoryCenterCoreFixtures() {
  const formalMemoryStore: FormalMemoryStoreV1 = {
    store_version: "formal_memory_store.v1",
    project_id: workflowProjectId,
    workflow_id: workflowId,
    revision: 7,
    records: [
      {
        memory_id: "mem:formal:offline:included",
        schema_version: "memory_governance.v1",
        record_version: 1,
        scope: {
          scope_id: "scope:project:offline",
          scope_type: "project",
          project_id: workflowProjectId,
          workflow_id: workflowId,
          role_ids: [],
          document_refs: [],
          model_export_policy: "local_only",
          valid_from: "2026-06-05T00:00:00Z",
        },
        memory_type: "project_memory",
        claim: "接口验收必须保留控制核心边界。",
        body: "active 正式记忆可以进入任务记忆包预览。",
        source_refs: [
          {
            source_ref_id: "source:memory-center:formal:001",
            source_type: "evidence",
            source_id: "evidence:m7",
            source_title: "M7 离线证据",
            captured_at: "2026-06-05T00:00:00Z",
            authority_level: "evidence",
            sensitive_level: "project",
          },
        ],
        status: "memory_active",
        supersedes_memory_id: null,
        superseded_by_memory_id: null,
        conflict_refs: [],
        audit_refs: [],
        created_at: "2026-06-05T00:00:00Z",
        updated_at: "2026-06-05T00:00:00Z",
      },
      {
        memory_id: "mem:formal:offline:blocked",
        schema_version: "memory_governance.v1",
        record_version: 1,
        scope: {
          scope_id: "scope:project:offline",
          scope_type: "project",
          project_id: workflowProjectId,
          workflow_id: workflowId,
          role_ids: ["codex-dev"],
          document_refs: [],
          model_export_policy: "blocked",
          valid_from: "2026-06-05T00:00:00Z",
        },
        memory_type: "project_memory",
        claim: "撤回来源不能进入任务记忆包。",
        body: "open blocking finding 必须阻断任务包入选。",
        source_refs: [
          {
            source_ref_id: "source:memory-center:formal:002",
            source_type: "director_review",
            source_id: "review:m7",
            source_title: "项目主管复核",
            captured_at: "2026-06-05T00:00:01Z",
            authority_level: "audit",
            sensitive_level: "private",
          },
        ],
        status: "memory_active",
        supersedes_memory_id: null,
        superseded_by_memory_id: null,
        conflict_refs: ["conflict:source-permission"],
        audit_refs: [],
        created_at: "2026-06-05T00:00:01Z",
        updated_at: "2026-06-05T00:00:01Z",
      },
    ],
    versions: [
      {
        version_id: "memver:memory-center:formal:001",
        memory_id: "mem:formal:offline:included",
        version_number: 1,
        change_type: "created",
        change_summary: "创建正式记忆第一版。",
        record_snapshot: {} as FormalMemoryStoreV1["records"][number],
        source_refs: [],
        changed_by_role: "project_director",
        reviewed_by: null,
        created_at: "2026-06-05T00:00:00Z",
      },
      {
        version_id: "memver:memory-center:formal:002",
        memory_id: "mem:formal:offline:blocked",
        version_number: 1,
        change_type: "created",
        change_summary: "创建正式记忆第一版。",
        record_snapshot: {} as FormalMemoryStoreV1["records"][number],
        source_refs: [],
        changed_by_role: "project_director",
        reviewed_by: null,
        created_at: "2026-06-05T00:00:01Z",
      },
    ],
    audit_events: [
      {
        audit_event_id: "audit:memory-center:formal:001",
        event_type: "memory_record_created",
        actor_id: "project-director-offline",
        actor_role: "project_director",
        project_id: workflowProjectId,
        workflow_id: workflowId,
        session_id: null,
        target_kind: "memory_record",
        target_id: "mem:formal:offline:included",
        before_state: null,
        after_state: "memory_active",
        reason: "M7 记忆中心离线测试。",
        source_refs: [],
        status: "succeeded",
        created_at: "2026-06-05T00:00:00Z",
      },
      {
        audit_event_id: "audit:memory-center:formal:002",
        event_type: "memory_record_created",
        actor_id: "project-director-offline",
        actor_role: "project_director",
        project_id: workflowProjectId,
        workflow_id: workflowId,
        session_id: null,
        target_kind: "memory_record",
        target_id: "mem:formal:offline:blocked",
        before_state: null,
        after_state: "memory_active",
        reason: "M7 记忆中心 lint 阻断离线测试。",
        source_refs: [],
        status: "succeeded",
        created_at: "2026-06-05T00:00:01Z",
      },
    ],
    updated_at: "2026-06-05T00:00:02Z",
    warnings: [],
  };
  formalMemoryStore.versions[0].record_snapshot = formalMemoryStore.records[0];
  formalMemoryStore.versions[1].record_snapshot = formalMemoryStore.records[1];

  const memoryCandidateStore: MemoryCandidateStoreV1 = {
    store_version: "memory_candidate_store.v1",
    project_id: workflowProjectId,
    workflow_id: workflowId,
    revision: 8,
    candidates: [
      {
        candidate_id: "memcand:memory-center:001",
        candidate_key: "memcand:v1:memory-center-review",
        schema_version: "memory_governance.v1",
        scope: {
          scope_id: "scope:project:offline",
          scope_type: "project",
          project_id: workflowProjectId,
          role_ids: [],
          document_refs: [],
          model_export_policy: "local_only",
          valid_from: "2026-06-05T00:00:02Z",
        },
        memory_type: "project_memory",
        claim: "候选需要确认要求和风险提示。",
        body: "candidate_confirmed 只表示候选保留，不代表正式记忆。",
        source_refs: [
          {
            source_ref_id: "source:memory-center:candidate:001",
            source_type: "observation_ref",
            source_id: "obs:v1:memory-center:001",
            source_title: "观察来源",
            captured_at: "2026-06-05T00:00:02Z",
            authority_level: "derived_summary",
            sensitive_level: "project",
          },
        ],
        generated_by_role: "project_director",
        generated_from: "observation:obs:v1:memory-center:001",
        status: "candidate_confirmed",
        risk_level: "medium",
        sensitive_level: "project",
        requires_user_confirmation: true,
        review_reason: "M7 记忆中心候选边界测试。",
        conflicts: [],
        audit_refs: [],
        adoption: null,
        created_at: "2026-06-05T00:00:02Z",
        updated_at: "2026-06-05T00:00:02Z",
      },
      {
        candidate_id: "memcand:memory-center:002",
        candidate_key: "memcand:v1:memory-center-adopted",
        schema_version: "memory_governance.v1",
        scope: {
          scope_id: "scope:project:offline",
          scope_type: "project",
          project_id: workflowProjectId,
          role_ids: [],
          document_refs: [],
          model_export_policy: "local_only",
          valid_from: "2026-06-05T00:00:03Z",
        },
        memory_type: "project_memory",
        claim: "采纳回链必须可见但仍保留候选身份。",
        body: "候选列表显示采纳回链，不把候选行显示成正式记忆。",
        source_refs: [],
        generated_by_role: "project_director",
        generated_from: "stage_handoff",
        status: "candidate_confirmed",
        risk_level: "low",
        sensitive_level: "project",
        requires_user_confirmation: true,
        review_reason: "M7 记忆中心采纳回链测试。",
        conflicts: [],
        audit_refs: [],
        adoption: {
          adopted_memory_id: "mem:formal:offline:included",
          adopted_version_id: "memver:memory-center:formal:001",
          adopted_audit_event_id: "audit:memory-center:formal:001",
          adopted_at: "2026-06-05T00:00:03Z",
          adopted_by_role: "project_director",
          adoption_reason: "项目主管受控采纳。",
        },
        created_at: "2026-06-05T00:00:03Z",
        updated_at: "2026-06-05T00:00:03Z",
      },
    ],
    events: [],
    updated_at: "2026-06-05T00:00:03Z",
  };

  const observationStore: ObservationStoreV1 = {
    store_version: "observation_store.v1",
    project_id: workflowProjectId,
    workflow_id: workflowId,
    revision: 4,
    observations: [
      {
        observation_id: "obs:v1:memory-center:001",
        observation_key: "obs:v1:memory-center-source",
        schema_version: "memory_observation.v1",
        project_id: workflowProjectId,
        workflow_id: workflowId,
        scope: {
          scope_id: "scope:project:offline",
          scope_type: "project",
          project_id: workflowProjectId,
          role_ids: [],
          document_refs: [],
          model_export_policy: "local_only",
          valid_from: "2026-06-05T00:00:02Z",
        },
        observation_type: "worker_report",
        summary: "开发线汇报形成观察来源。",
        source_refs: [
          {
            source_ref_id: "obs-source:memory-center:001",
            source_kind: "worker_report",
            source_id: "worker-report:m7",
            project_id: workflowProjectId,
            workflow_id: workflowId,
            summary: "worker 报告摘要。",
            sensitive_level: "internal",
            created_at: "2026-06-05T00:00:02Z",
          },
        ],
        status: "candidate_created",
        generated_by_role: "worker",
        actor_id: "codex-dev",
        risk_level: "low",
        sensitive_level: "internal",
        candidate_key: "memcand:v1:memory-center-review",
        audit_refs: [],
        created_at: "2026-06-05T00:00:02Z",
        updated_at: "2026-06-05T00:00:02Z",
      },
    ],
    events: [],
    updated_at: "2026-06-05T00:00:02Z",
    warnings: [],
  };

  const memoryCaptureStore: MemoryCaptureStoreV1 = {
    store_version: "memory_capture_store.v1",
    project_id: workflowProjectId,
    workflow_id: workflowId,
    revision: 3,
    events: [
      {
        capture_event_id: "capture:memory-center:candidate",
        event_key: "memory-center:candidate",
        schema_version: "memory_capture_event.v1",
        source_type: "worker_report",
        source_ref_id: "worker-report:m7",
        project_id: workflowProjectId,
        workflow_id: workflowId,
        workflow_node_id: `${workflowId}:node:developer`,
        run_unit_id: "run-unit:memory-center:developer",
        product_command_id: null,
        product_attempt_id: null,
        runtime_log_ref: "runtime-log:memory-center:candidate",
        audit_refs: ["audit:memory-center:candidate"],
        readback_ref: null,
        task_package_ref: "task-package:memory-center",
        memory_packet_ref: "memory-packet:memory-center",
        summary: "开发线汇报形成候选来源。",
        evidence_summary: "离线记忆中心 fixture。",
        sensitivity: "internal",
        candidate_policy: "candidate_allowed",
        blocked_reason: null,
        observation_id: "obs:v1:memory-center:001",
        candidate_key: "memcand:v1:memory-center-review",
        created_by: "project_director",
        created_at: "2026-06-05T00:00:02Z",
        updated_at: "2026-06-05T00:00:02Z",
      },
      {
        capture_event_id: "capture:memory-center:needs-proof",
        event_key: "memory-center:needs-proof",
        schema_version: "memory_capture_event.v1",
        source_type: "readback",
        source_ref_id: "readback:memory-center",
        project_id: workflowProjectId,
        workflow_id: workflowId,
        workflow_node_id: `${workflowId}:node:developer`,
        run_unit_id: "run-unit:memory-center:developer",
        product_command_id: "product-command:memory-center",
        product_attempt_id: "attempt:memory-center",
        runtime_log_ref: "runtime-log:memory-center:needs-proof",
        audit_refs: ["audit:memory-center:needs-proof"],
        readback_ref: "readback:memory-center",
        task_package_ref: "task-package:memory-center",
        memory_packet_ref: "memory-packet:memory-center",
        summary: "捕获事件声明允许候选但缺少回链。",
        evidence_summary: "离线记忆中心补证 fixture。",
        sensitivity: "internal",
        candidate_policy: "candidate_allowed",
        blocked_reason: null,
        observation_id: null,
        candidate_key: null,
        created_by: "project_director",
        created_at: "2026-06-05T00:00:07Z",
        updated_at: "2026-06-05T00:00:07Z",
      },
    ],
    updated_at: "2026-06-05T00:00:07Z",
    warnings: [],
  };

  return {
    formalMemoryStore,
    memoryCandidateStore,
    observationStore,
    memoryCaptureStore,
  };
}
