import { deriveAgentAdapterDescriptors } from "../../src/lib/adapterCapabilities";
import { deriveProviderAvailabilitySummaries } from "../../src/lib/providerAvailability";
import { deriveSessionOperationDescriptors } from "../../src/lib/sessionOperations";
import type {
  AgentAdapterDescriptor,
  OperationControlItem,
  PluginRecord,
  ProjectRecord,
  SessionRecord,
  SkillRecord,
  WorkbenchSnapshot,
} from "../../src/lib/types";
import { diagnosticSummaryFixture, runtimeLogStoreFixture } from "./offlineRuntimeDiagnosticFixtures";

export function workbenchBaseFixtures(): {
  backendAgentAdapterDescriptors: AgentAdapterDescriptor[];
  backendProviderAvailabilitySummaries: ReturnType<typeof deriveProviderAvailabilitySummaries>;
  backendSessionOperationDescriptors: ReturnType<typeof deriveSessionOperationDescriptors>;
  emptyProject: ProjectRecord;
  otherProjectSession: SessionRecord;
  plugin: PluginRecord;
  project: ProjectRecord;
  session: SessionRecord;
  skill: SkillRecord;
  snapshot: WorkbenchSnapshot;
  workflowId: string;
  workflowProjectId: string;
} {
  const project: ProjectRecord = {
    project_root: "/offline-fixture/projects/codex-workbench",
    name: "codex-workbench",
    active_hint: true,
    thread_count: 2,
    active_thread_count: 1,
    archived_thread_count: 1,
    latest_updated_at_ms: 1_764_000_000_000,
    authority_files: [],
    handoff_files: [],
    evidence_files: [],
    harness_candidates: [
      {
        entry_type: "package_script",
        name: "test:offline",
        path: "/offline-fixture/projects/codex-workbench/package.json",
        source: "package.json",
        size_bytes: 512,
        updated_at_ms: 1_764_000_000_000,
        warnings: [],
      },
    ],
    harness_resources: [
      {
        root_path: "/offline-fixture/projects/codex-workbench/harness",
        display_name: "offline folder harness",
        harness_kind: "codex_harness",
        agent_type: "codex",
        adapter_id: "codex-local",
        source_kind: "derived",
        capabilities: ["codex", "harness"],
        manifest_path: null,
        readme_path: null,
        version: null,
        entrypoints: [
          {
            entry_type: "node_script",
            name: "check.js",
            path: "/offline-fixture/projects/codex-workbench/harness/check.js",
            source_kind: "project_file",
            size_bytes: 128,
            updated_at_ms: 1_764_000_000_000,
            warnings: [],
          },
        ],
        permission_level: "read_only",
        size_bytes: 96,
        updated_at_ms: 1_764_000_000_000,
        warnings: ["missing_manifest", "missing_readme", "missing_version"],
      },
      {
        root_path: "/offline-fixture/projects/codex-workbench/weak-harness",
        display_name: "offline weak harness",
        harness_kind: "codex_harness",
        agent_type: "codex",
        adapter_id: "codex-local",
        source_kind: "derived",
        capabilities: [],
        manifest_path: null,
        readme_path: null,
        version: null,
        entrypoints: [],
        permission_level: "read_only",
        size_bytes: 64,
        updated_at_ms: 1_764_000_000_000,
        warnings: ["missing_manifest", "missing_readme", "missing_entrypoints", "missing_version"],
      },
    ],
    context_warnings: [],
    warnings: [],
  };

  const skill: SkillRecord = {
    skill_id: "offline-skill",
    title: "Offline Skill",
    description: "Fixture skill",
    path: "/offline-fixture/skills/offline",
    source_type: "plugin",
    plugin_name: "offline-plugin",
    plugin_version: "1.0.0",
    warnings: [],
  };

  const plugin: PluginRecord = {
    plugin_name: "offline-plugin",
    plugin_version: "1.0.0",
    homepage: null,
    skill_count: 1,
    has_apps: false,
    has_mcp_servers: false,
    warnings: [],
  };

  const session: SessionRecord = {
    thread_id: "offline-thread-001",
    title: "Offline interaction fixture",
    project_root: project.project_root,
    updated_at_ms: 1_764_000_000_000,
    archived: false,
    rollout_exists: true,
    rollout_path: "/offline-fixture/rollouts/offline-thread-001.jsonl",
    model: "offline-model",
    reasoning_effort: "offline",
    thread_source: "offline-fixture",
    warnings: [],
  };

  const otherProjectSession: SessionRecord = {
    ...session,
    thread_id: "offline-thread-other-project",
    title: "Other project session",
    project_root: "/offline-fixture/projects/other-project",
    rollout_path: "/offline-fixture/rollouts/offline-thread-other-project.jsonl",
  };

  const backendAgentAdapterDescriptor: AgentAdapterDescriptor = {
    ...deriveAgentAdapterDescriptors({
      sessions: [session, otherProjectSession],
      projects: [project],
      workflowState: null,
    })[0],
    source_kind: "backend_read_model",
    warnings: [
      "adapter_descriptor_is_backend_read_model_only",
      "does_not_change_codex_execution_semantics",
      "unimplemented_adapters_hidden",
    ],
  };

  const backendAgentAdapterDescriptors: AgentAdapterDescriptor[] = [
    backendAgentAdapterDescriptor,
    ...deriveAgentAdapterDescriptors({
      sessions: [session, otherProjectSession],
      projects: [project],
      workflowState: null,
    })
      .slice(1)
      .map((descriptor) => ({
        ...descriptor,
        source_kind: "backend_read_model" as const,
      })),
  ];
  const backendSessionOperationDescriptors = deriveSessionOperationDescriptors(backendAgentAdapterDescriptors);
  const backendProviderAvailabilitySummaries = deriveProviderAvailabilitySummaries(
    backendAgentAdapterDescriptors,
    backendSessionOperationDescriptors,
  );

  const emptyProject: ProjectRecord = {
    ...project,
    project_root: "/offline-fixture/projects/empty-project",
    name: "empty-project",
    thread_count: 0,
    active_thread_count: 0,
    archived_thread_count: 0,
  };
  const operationControlOperation = (
    operationId: "retry" | "stop" | "restart" | "resume",
    label: string,
    gate: string,
    wouldWriteIfReal: string,
    riskDisclosure: string,
  ): OperationControlItem => ({
    operation_id: operationId,
    label,
    status: "available",
    applies_to: operationId === "retry" ? "failed_run_unit" : operationId === "stop" ? "running_session_only" : "bound_or_existing_session",
    would_write_if_real: wouldWriteIfReal,
    current_gate: gate,
    does_execute_in_l3: false,
    status_after_confirmation: "confirmed_recorded",
    requires_separate_authorized_window: true,
    risk_disclosure: riskDisclosure,
    confirmation_label: `确认记录 ${label} 决策`,
    audit_event_type: "operation_decision_recorded",
    runtime_status_after_confirmation: "operation_decision_recorded_pending_real_authorization",
    readback_status: "not_attempted_l3_decision_only",
    readback_result_count: null,
    blocks_k3_b2: true,
    user_visible_summary: `${label} 在 L3 只会记录决策，不会触发真实操作。`,
    developer_details: [
      { label: "operation_id", value: operationId },
      { label: "current_gate", value: gate },
      { label: "status_after_confirmation", value: "confirmed_recorded" },
      { label: "does_execute_in_l3", value: "false" },
    ],
    warnings: ["decision_only_control_surface", "confirmed_recorded_is_not_executed"],
  });
  const operationControlOperations = [
    operationControlOperation(
      "retry",
      "重试",
      "requires_user_confirmation_and_new_authorized_window",
      "workbench_state_only",
      "确认后只记录重试请求和风险确认；不会自动重试，不调用 runner。",
    ),
    operationControlOperation(
      "stop",
      "停止",
      "blocked_no_runtime_handle",
      "workbench_state_only",
      "确认后只记录停止请求；当前没有真实 runtime handle，不会 kill 进程或会话。",
    ),
    operationControlOperation(
      "restart",
      "重启",
      "blocked_restart_semantics_not_defined",
      "codex_home_and_workbench_state",
      "确认后只记录重启意图；不会新建会话、resume 旧会话或重跑任务。",
    ),
    operationControlOperation(
      "resume",
      "恢复",
      "gated_real_resume_mario_test_only",
      "codex_home_and_workbench_state",
      "确认后只记录恢复决策；不会进入 real-resume phase B，也不扩大既有门。",
    ),
  ];

  const snapshot: WorkbenchSnapshot = {
    summary: {
      generated_at: "2026-05-28T00:00:00Z",
      project_count: 1,
      session_count: 1,
      skill_count: 1,
      plugin_count: 1,
      task_count: 0,
      warning_count: 0,
    },
    projects: [project],
    sessions: [session],
    skills: [skill],
    plugins: [plugin],
    tasks: [],
    agent_adapters: backendAgentAdapterDescriptors,
    session_operations: backendSessionOperationDescriptors,
    provider_availability: backendProviderAvailabilitySummaries,
    session_continuation_previews: [],
    session_continuation_store: {
      schema_version: "session_continuation_store.v1",
      store_version: 1,
      storage_kind: "sidecar_json_v0",
      scope: {
        scope_kind: "workflow_state_sidecar",
        workflow_state_path: "/offline-fixture/workflow-state.v0.json",
        sidecar_path: "/offline-fixture/session-continuations.v1.json",
        project_roots: [],
      },
      revision: 0,
      last_write_id: null,
      generated_by: "offline-test",
      created_at: "2026-06-06T00:00:00Z",
      updated_at: "2026-06-06T00:00:00Z",
      continuations: [],
      attempts: [],
      audit_events: [],
      warnings: [],
    },
    runtime_session_attention: [],
    session_run_status_summaries: [],
    runtime_log_store: runtimeLogStoreFixture(project.project_root, session.thread_id),
    worker_protocol: {
      schema_version: "worker_protocol_read_model.v1",
      generated_at: "2026-05-28T00:00:00Z",
      source_policy: "offline fixture; no worker execution.",
      worker_adapters: [],
      work_threads: [],
      run_units: [],
      credential_requirements: [],
      external_call_risk_envelopes: [],
      project_capability_policies: [],
      run_relations: [],
      worker_lanes: [],
      multi_worker_dispatch_plans: [],
      adapter_contract_checklists: [],
      controlled_api_cli_semantics: [],
      diagnostic_event_schemas: [],
      adapter_health_summaries: [],
      adapter_degraded_modes: [],
      adapter_data_locations: [],
      dispatch_requests: [],
      dispatch_guards: [],
      permission_envelopes: [],
      task_memory_packet_refs: [],
      worker_handoffs: [],
      readback_results: [],
      worker_report_candidates: [],
      warnings: [],
    },
    real_execution_product_commands: {
      schema_version: "real_execution_product_commands.v1",
      sidecar_name: "real-execution-product-commands.v1.json",
      sidecar_path: "/offline-fixture/real-execution-product-commands.v1.json",
      store_available: false,
      store_revision: 0,
      command_count: 0,
      pending_decision_count: 0,
      running_attempt_count: 0,
      blocked_attempt_count: 0,
      last_attempt_status: null,
      failure_stop_retry_summary: {
        schema_version: "real_execution_product_command_failure_stop_retry.v1",
        item_count: 0,
        failure_count: 0,
        blocked_count: 0,
        readback_issue_count: 0,
        manual_stop_requested_count: 0,
        retry_requires_new_user_confirmation: false,
        items: [],
        warnings: ["pcr7_failure_stop_retry_empty_fixture"],
      },
      ordinary_product_entry_status: "readiness_only_pcr1_no_execute",
      legacy_entry_status: "legacy_sealed_blocked_not_product_command",
      runner_entry_status: "internal_runner_blocked_until_unified_execute_and_level_b",
      level_b_authorization_required: true,
      warnings: ["pcr1_read_model_fixture"],
    },
    project_workflow_automation: {
      schema_version: "project_workflow_automation.v1",
      available: false,
      generated_at: "2026-06-09T00:00:00Z",
      latest_automation_id: null,
      latest_status: null,
      latest_plan: null,
      run_unit_count: 0,
      waiting_user_count: 0,
      blocked_count: 0,
      readback_unknown_count: 0,
      worker_report_count: 0,
      capture_event_count: 0,
      observation_count: 0,
      next_step: null,
      warnings: ["project_workflow_automation_not_recorded"],
    },
    k3_b1_recovery: {
      schema_version: "k3_b1_recovery_read_model.v1",
      execution_point_id: "stage-k-k3-b1-mario-test-workflow-read-only",
      current_state: "blocked_by_safety_review_again",
      k3_b2_gate: {
        blocked: true,
        status: "blocked_waiting_k3_b1_recovery_acceptance",
        reason: "K3-B1 仍未被主管线接受为成功或等价恢复；K3-B2 继续阻断。",
      },
      recovery_options: [
        {
          option_id: "manual_exact_command_submission",
          label: "用户手动运行 exact command 并回交",
          status_after_selection: "manual_recovery_available",
          user_visible_description: "用户手动运行冻结命令并回交脱敏摘要，主管线复核前不改变成功状态。",
          does_execute_codex: false,
          requires_separate_task_package: false,
        },
        {
          option_id: "renewed_risk_approval_request",
          label: "重新明确批准风险后另行申请真实执行",
          status_after_selection: "pending_renewed_risk_approval",
          user_visible_description: "L1 只进入待重新授权/待安全审查。",
          does_execute_codex: false,
          requires_separate_task_package: true,
        },
        {
          option_id: "narrow_local_bridge_design",
          label: "设计更窄的本地执行桥",
          status_after_selection: "narrow_bridge_design_required",
          user_visible_description: "只作为后续设计候选，不能绕过安全审查。",
          does_execute_codex: false,
          requires_separate_task_package: true,
        },
      ],
      manual_exact_command: {
        source_task_ref: "tasks/2026-06-10-stage-k-k3-b1-mario-test-workflow-read-only-real-resume-run-v1.md#6",
        source_evidence_ref: "evidence/2026-06-10-stage-k-k3-b1-retry-safety-review-rejection-v1.md#申请执行的冻结命令",
        working_directory: "/Users/yoyi/workspace/product-line/prototypes/productized-desktop-shell/src-tauri",
        command_lines: [
          "K3_B1_REAL_EXECUTION_AUTHORIZED=stage-k-k3-b1-mario-test-workflow-read-only",
          "K3_B1_PROJECT_ROOT=/Users/yoyi/Documents/mario test",
          "K3_B1_SESSION_ID=019e798a-ac37-7771-b982-e38084fcd22e",
          "K3_B1_EXPECTED_MARKER=K3_B1_MARIO_TEST_WORKFLOW_READ_ONLY_OK_2026_06_10",
          "K3_B1_WORKFLOW_STATE_PARENT=/Users/yoyi/workspace/product-line/tmp/k3-b-real-workflow-automation/runs",
          "K3_B1_PROMPT_PATH=/Users/yoyi/workspace/product-line/tmp/k3-b-real-workflow-automation/prompts/k3-b1-mario-test-read-only.prompt.txt",
          "cargo test --lib project_workflow_automation::tests::k3_b1_real_mario_test_workflow_resume_requires_env_authorization -- --ignored --exact --nocapture",
        ],
        prompt_ref: "prompt:stage-k:k3:b1:mario-test-workflow-read-only",
        prompt_hash: "ab0442e86e75900ab47b293328e4a2b46512ae68868799b94e8608ffedd57039",
        prompt_path_ref: "tmp/k3-b-real-workflow-automation/prompts/k3-b1-mario-test-read-only.prompt.txt",
        prompt_body_included: false,
        user_execution_required: true,
        workbench_executes_in_l1: false,
        runs_real_codex_if_user_executes: true,
        writes_codex_home_if_user_executes: true,
        boundary: "L1 只展示冻结 exact command，供用户在自己明确控制的终端环境手动执行并回交；工作台不执行、不发送 prompt、不读取或写入 .codex。",
      },
      manual_submission_contract: {
        status_after_submit: "manual_recovery_needs_review",
        auto_accepts_success: false,
        required_fields: [
          "stdout_summary",
          "stderr_summary",
          "exit_code",
          "run_dir",
          "last_message",
          "sidecar_refs",
          "runtime_log_refs",
          "audit_refs",
          "readback_status",
          "result_count",
          "project_file_hashes_before_after",
          "user_statement",
        ],
        sensitive_material_policy: "如回交材料包含 secret/token/完整 transcript/.codex 原始内容，必须阻断或先脱敏。",
      },
      renewed_risk_approval: {
        status_after_request: "pending_renewed_risk_approval",
        inherited_authorization_allowed: false,
        warning: "重新申请必须让用户明确看到 prompt 外发和 /Users/yoyi/.codex 写入风险。",
      },
      narrow_bridge_design: {
        status_after_selection: "narrow_bridge_design_required",
        implementation_allowed_in_l1: false,
        minimum_future_fields: ["allowed_roots", "denied_paths", "prompt_hash", "readback", "audit", "rollback", "user_confirmation"],
      },
      runtime_boundary: {
        records_blocked_state: true,
        records_recovery_choice: true,
        stores_prompt_body: false,
        stores_codex_home_content: false,
        allowed_summary: "只记录 blocked 状态、恢复选择、是否等待复核和引用。",
      },
      audit_boundary: {
        event_type: "k3_b1_recovery_decision_recorded",
        records_actor: true,
        records_choice: true,
        records_supervisor_review: true,
        stores_sensitive_material: false,
      },
      readback_boundary: {
        status: "not_attempted_l1_recovery_path_only",
        result_count: null,
        unavailable_reason: "L1 未执行真实 Codex；读回结果未知/不可用，不能显示为 0 条。",
        user_submitted_evidence_only: true,
      },
      memory_capture_boundary: {
        capture_event_allowed: true,
        observation_allowed: true,
        candidate_allowed: true,
        formal_memory_auto_write: false,
        suggested_candidate_text:
          "K3-B1 retry 曾因真实 Codex resume 的外发和 .codex 写入风险被安全审查再次阻断；后续恢复需要用户手动回交、重新授权申请或更窄本地执行桥。",
      },
      user_summary: [
        "K3-B1 被安全审查再次阻断。",
        "阻断原因：真实 Codex resume 会向外部服务发送项目/session 派生 prompt，并写入 Codex 本地状态。",
        "合法恢复：手动运行并回交、重新授权申请、或等待更窄本地执行桥设计。",
        "当前不能自动重试，不能进入 K3-B2，也不能把手动回交自动当成功。",
      ],
      developer_details: [
        { label: "execution_point_id", value: "stage-k-k3-b1-mario-test-workflow-read-only" },
        { label: "prompt_hash", value: "ab0442e86e75900ab47b293328e4a2b46512ae68868799b94e8608ffedd57039" },
      ],
      warnings: ["k3_b1_still_blocked", "k3_b2_gate_remains_blocked", "manual_submission_requires_supervisor_review"],
    },
    operation_control: {
      schema_version: "operation_control_read_model.v1",
      generated_at: "2026-06-16T00:00:00Z",
      status_contract: ["not_applicable", "available", "pending_confirmation", "confirmed_recorded", "rejected", "blocked"],
      operations: operationControlOperations,
      audit_boundary: {
        event_type: "operation_decision_recorded",
        records_actor: true,
        records_operation: true,
        records_risk_acknowledgement: true,
        records_supervisor_review: true,
        stores_sensitive_material: false,
      },
      runtime_boundary: {
        records_operation_kind: true,
        records_operation_status: true,
        records_pending_state: true,
        real_process_control: false,
        stores_prompt_body: false,
        stores_codex_home_content: false,
        allowed_summary: "只记录操作决策、待处理状态和引用；不记录 prompt body、secret、完整 transcript 或 .codex 原文。",
      },
      readback_boundary: {
        status: "not_attempted_l3_decision_only",
        result_count: null,
        unavailable_reason: "L3 不执行真实操作；readback 未发生，结果数未知/不可用。",
        real_readback_performed: false,
        user_submitted_evidence_only: true,
      },
      memory_capture_boundary: {
        capture_event_allowed: true,
        observation_allowed: true,
        candidate_allowed: true,
        formal_memory_auto_write: false,
        suggested_candidate_text: "用户对运行控制发起了产品确认；该决策已记录待处理，未触发真实执行。",
      },
      true_operation_available: false,
      k3_b2_unlocked: false,
      user_summary: [
        "retry / stop / restart / resume 现在是可确认、可审计、可回收的产品控制面。",
        "确认只记录决策和待处理状态，不执行真实操作，不显示成功。",
        "真实 retry / stop / restart / resume 必须另开独立授权窗口。",
      ],
      warnings: [
        "operation_control_l3_decision_only",
        "confirmed_recorded_is_not_executed",
        "no_real_retry_stop_restart_resume",
        "k3_b2_remains_blocked",
      ],
    },
    page_read_model_inventory: {
      schema_version: "workbench_page_read_model_inventory.v1",
      generated_at: "2026-06-11T00:00:00Z",
      status: "contract_only",
      source_policy: "offline fixture",
      contracts: [],
      warnings: [],
    },
    diagnostic_summary: diagnosticSummaryFixture(),
    diagnostics: {
      index_path: "/offline-fixture/index.json",
      tasks_path: "/offline-fixture/tasks.md",
      generated_at: "2026-05-28T00:00:00Z",
      top_level_warning_count: 0,
      context_warning_count: 0,
      allowed_project_path_count: 1,
      allowed_rollout_path_count: 1,
      release_bundle_enabled: false,
      notes: [],
    },
  };

  return {
    backendAgentAdapterDescriptors,
    backendProviderAvailabilitySummaries,
    backendSessionOperationDescriptors,
    emptyProject,
    otherProjectSession,
    plugin,
    project,
    session,
    skill,
    snapshot,
    workflowId: "workflow:offline-fixture-projects-codex-workbench:default",
    workflowProjectId: "project:offline-fixture-projects-codex-workbench",
  };
}
