import type {
  MemoryEntityRelationPreviewOutput,
  MemoryEntityRelationStoreV1,
  MemoryLintStoreV1,
} from "../../src/lib/types";

export function memoryCenterGovernanceFixtures(): {
  memoryLintStore: MemoryLintStoreV1;
  memoryEntityRelationStore: MemoryEntityRelationStoreV1;
  memoryEntityRelationPreview: MemoryEntityRelationPreviewOutput;
} {
  const memoryLintStore: MemoryLintStoreV1 = {
    store_version: "memory_lint_store.v1",
    project_id: "project:offline-fixture-projects-codex-workbench",
    workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
    revision: 6,
    findings: [
      {
        finding_id: "memlint:memory-center:blocking",
        schema_version: "memory_governance.v1",
        finding_type: "source_permission_revoked",
        severity: "blocking",
        status: "open",
        source_kind: "memory_record",
        source_id: "mem:formal:offline:blocked",
        target_memory_id: "mem:formal:offline:blocked",
        target_candidate_key: null,
        scope_type: "project",
        memory_type: "project_memory",
        claim: "撤回来源不能进入任务记忆包。",
        summary: "来源权限撤回产生 open blocking finding。",
        recommended_action: "exclude_from_task_packet",
        evidence_refs: [],
        audit_event_id: null,
        created_at: "2026-06-05T00:00:04Z",
        updated_at: "2026-06-05T00:00:04Z",
      },
      {
        finding_id: "memlint:memory-center:review",
        schema_version: "memory_governance.v1",
        finding_type: "candidate_conflicts_with_active_memory",
        severity: "needs_review",
        status: "open",
        source_kind: "memory_candidate",
        source_id: "memcand:v1:memory-center-review",
        target_memory_id: "mem:formal:offline:included",
        target_candidate_key: "memcand:v1:memory-center-review",
        scope_type: "project",
        memory_type: "project_memory",
        claim: "候选需要确认要求和风险提示。",
        summary: "候选与 active 记忆需要人工复核。",
        recommended_action: "block_adoption",
        evidence_refs: [],
        audit_event_id: null,
        created_at: "2026-06-05T00:00:05Z",
        updated_at: "2026-06-05T00:00:05Z",
      },
    ],
    runs: [
      {
        run_id: "memlint-run:memory-center",
        lint_intent: "task_packet_guard",
        actor_id: "system",
        actor_role: "system",
        finding_ids: ["memlint:memory-center:blocking"],
        blocking_count: 1,
        status: "blocked",
        reason: "task packet guard blocked by revoked source",
        report_id: null,
        created_at: "2026-06-05T00:00:06Z",
      },
      {
        run_id: "memlint-run:memory-center:maintenance",
        lint_intent: "maintenance_run",
        actor_id: "project-director-memory-center",
        actor_role: "project_director",
        finding_ids: ["memlint:memory-center:blocking", "memlint:memory-center:review"],
        blocking_count: 1,
        status: "blocked",
        reason: "maintenance_run found 1 blocking finding(s)",
        report_id: "memory-maintenance-report:v1:offline",
        created_at: "2026-06-05T00:00:07Z",
      },
    ],
    maintenance_reports: [
      {
        report_id: "memory-maintenance-report:v1:offline",
        run_id: "memlint-run:memory-center:maintenance",
        checked_memory_count: 2,
        checked_candidate_count: 2,
        checked_observation_count: 1,
        checked_relation_count: 1,
        open_count: 2,
        blocking_count: 1,
        needs_review_count: 1,
        info_count: 0,
        check_summaries: [
          {
            check_kind: "permission_revocation",
            checked_count: 2,
            finding_count: 1,
            blocking_count: 1,
            needs_review_count: 0,
            info_count: 0,
            display_text: "权限撤回：checked 2 / finding 1 / blocking 1 / needs_review 0 / info 0",
          },
          {
            check_kind: "entity_relation_drift",
            checked_count: 2,
            finding_count: 1,
            blocking_count: 0,
            needs_review_count: 1,
            info_count: 0,
            display_text: "实体 / 关系漂移：checked 2 / finding 1 / blocking 0 / needs_review 1 / info 0",
          },
        ],
        recommendations: [
          {
            recommendation_id: "memory-maintenance-recommendation:v1:offline",
            severity: "blocking",
            target_kind: "memory_record",
            target_id: "mem:formal:offline:blocked",
            action_label: "review_source_permission",
            display_text: "source_permission_revoked：来源权限撤回产生 open blocking finding；建议人工复核，不会自动执行 lifecycle",
          },
        ],
        index_status: {
          status: "stale",
          formal_store_revision: 4,
          lint_store_revision: 6,
          entity_relation_store_revision: 2,
          checked_at: "2026-06-05T00:00:07Z",
          display_text: "索引状态 stale：formal rev 4 / entity-relation rev 2；状态 finding 不会重建索引或改变事实",
          warnings: ["derived_index_status_requires_review"],
        },
        display_text: "维护任务摘要：检查正式记忆 2 / 候选 2 / observation 1 / relation 1；open 2 / blocking 1 / needs_review 1 / info 0。维护任务只生成 finding，不会自动修改正式记忆。",
        warnings: ["memory_maintenance_findings_only"],
        created_at: "2026-06-05T00:00:07Z",
      },
    ],
    updated_at: "2026-06-05T00:00:06Z",
    warnings: [],
  };

  const memoryEntityRelationStore: MemoryEntityRelationStoreV1 = {
    store_version: "memory_entity_relations.v1",
    project_id: "project:offline-fixture-projects-codex-workbench",
    workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
    revision: 2,
    registry: {
      entities: [
        {
          entity_id: "entity:v1:tool:codex",
          entity_kind: "tool",
          canonical_key: "tool:codex",
          display_name: "Codex CLI",
          aliases: [
            {
              alias_id: "entity-alias:v1:codex",
              alias: "codex tool",
              source_kind: "formal_memory",
              source_id: "mem:formal:offline:included",
              created_at: "2026-06-05T00:00:07Z",
            },
          ],
          source_refs: [
            {
              source_kind: "formal_memory",
              source_id: "mem:formal:offline:included",
              source_path: null,
              source_title: "接口验收必须保留控制核心边界。",
              authority_level: "formal_memory",
              sensitive_level: "project",
            },
          ],
          status: "registered",
          created_at: "2026-06-05T00:00:07Z",
          updated_at: "2026-06-05T00:00:07Z",
          warnings: [],
        },
      ],
      updated_at: "2026-06-05T00:00:07Z",
      warnings: ["memory_entity_registry_minimal"],
    },
    entity_candidates: [],
    merge_candidates: [],
    relation_candidates: [],
    relations: [
      {
        relation_id: "relation:v1:memory-center:001",
        relation_kind: "causal",
        subject_entity_id: "entity:v1:memory_record:included",
        object_entity_id: "entity:v1:knowledge_doc:contract",
        subject_label: "接口验收必须保留控制核心边界。",
        object_label: "接口契约资料",
        predicate: "causal_candidate",
        source_kind: "manual",
        source_refs: [
          {
            source_kind: "manual",
            source_id: "manual:contract-change",
            source_path: null,
            source_title: "接口契约资料",
            authority_level: "evidence",
            sensitive_level: "project",
          },
        ],
        status: "confirmed",
        confirmed_by: "project_director",
        confirmation_role: "project_director",
        confirmation_reason: "项目主管确认低风险本项目因果关系。",
        created_at: "2026-06-05T00:00:08Z",
        updated_at: "2026-06-05T00:00:08Z",
        warnings: ["confirmed_relation_explains_retrieval_only"],
      },
    ],
    audit_events: [
      {
        audit_event_id: "audit:memory-relation:v1:offline",
        event_type: "memory_relation_candidate_decision_recorded",
        actor_id: "project-director-memory-center",
        actor_role: "project_director",
        target_kind: "memory_relation_candidate",
        target_id: "relation-candidate:v1:offline",
        before_status: "candidate",
        after_status: "confirmed",
        reason: "确认关系候选。",
        created_at: "2026-06-05T00:00:08Z",
        warnings: [],
      },
    ],
    updated_at: "2026-06-05T00:00:08Z",
    warnings: ["memory_entity_relation_store_m10_minimal_sidecar"],
  };

  const memoryEntityRelationPreview: MemoryEntityRelationPreviewOutput = {
    store_revision: memoryEntityRelationStore.revision,
    entity_candidates: [
      {
        candidate_id: "entity-candidate:v1:codex-cli",
        entity_kind: "tool",
        display_name: "Codex CLI",
        normalized_key: "tool:codex",
        source_kind: "formal_memory",
        source_id: "mem:formal:offline:included",
        source_path: null,
        source_title: "Codex CLI",
        source_refs: [],
        confidence_kind: "source_ref",
        status: "candidate",
        reason: "来源引用派生实体候选。",
        created_at: "2026-06-05T00:00:09Z",
        warnings: [],
      },
    ],
    merge_candidates: [
      {
        merge_candidate_id: "entity-merge-candidate:v1:codex",
        left_entity_candidate_id: "entity-candidate:v1:codex-cli",
        right_entity_candidate_id: "entity-candidate:v1:codex-tool",
        left_label: "Codex CLI",
        right_label: "codex tool",
        normalized_key: "tool:codex",
        source_kind: "similarity_hit",
        status: "candidate",
        requires_user_confirmation: false,
        reason: "相似度命中仅作候选，需人工确认后才会登记实体合并决定。",
        created_at: "2026-06-05T00:00:09Z",
        warnings: [],
      },
    ],
    relation_candidates: [
      {
        candidate_id: "relation-candidate:v1:contract",
        relation_kind: "causal",
        subject_entity_id: "entity:v1:memory_record:included",
        object_entity_id: "entity:v1:knowledge_doc:contract",
        subject_label: "接口验收必须保留控制核心边界。",
        object_label: "接口契约资料",
        predicate: "causal_candidate",
        source_kind: "manual",
        source_refs: [],
        confidence_kind: "deterministic_source_ref",
        status: "candidate",
        requires_user_confirmation: false,
        reason: "待确认因果关系；确认后才可用于解释召回原因。",
        created_at: "2026-06-05T00:00:09Z",
        warnings: [],
      },
      {
        candidate_id: "relation-candidate:v1:llm",
        relation_kind: "causal",
        subject_entity_id: "entity:v1:memory_record:included",
        object_entity_id: "entity:v1:proposal:llm",
        subject_label: "接口验收必须保留控制核心边界。",
        object_label: "LLM 因果推断",
        predicate: "llm_inferred_candidate",
        source_kind: "llm_inferred",
        source_refs: [],
        confidence_kind: "llm_inferred_candidate_only",
        status: "candidate",
        requires_user_confirmation: true,
        reason: "LLM 推断仅作候选，不能直接进入已确认关系。",
        created_at: "2026-06-05T00:00:09Z",
        warnings: [],
      },
    ],
    summary: {
      sidecar_name: "memory-entity-relations.v1.json",
      revision: memoryEntityRelationStore.revision,
      entity_count: 1,
      entity_candidate_count: 1,
      merge_candidate_count: 1,
      relation_candidate_count: 2,
      confirmed_relation_count: 1,
      display_text: "实体 / 关系治理 fixture。",
      warnings: [],
    },
    warnings: ["llm_inferred_relation_candidate_only", "similarity_hit_candidate_only"],
  };

  return {
    memoryLintStore,
    memoryEntityRelationStore,
    memoryEntityRelationPreview,
  };
}
