import type { SessionRecord, WorkflowStateSnapshot } from "../../src/lib/types";

export function projectWorkflowStateFixtures(projectRoot: string, session: SessionRecord) {
  const workflowState: WorkflowStateSnapshot = {
    exists: false,
    path: "/offline-fixture/Application Support/CodexGovernanceWorkbench/workflow-state/workflow-state.v0.json",
    schema_version: null,
    workflow_version: null,
    workspace_id: null,
    updated_at: null,
    initialized: false,
    counts: {
      projects: 0,
      agent_adapters: 0,
      workflows: 0,
      nodes: 0,
      edges: 0,
      work_items: 0,
      artifacts: 0,
      reviews: 0,
      audit_events: 0,
      capabilities: 0,
      harness_resources: 0,
    },
    project_workflows: [],
    warnings: ["状态文件不存在；不会自动创建。"],
  };

  const workflowStateWithProjectWorkflow: WorkflowStateSnapshot = {
    ...workflowState,
    exists: true,
    schema_version: "workflow_state_v0",
    workflow_version: 1,
    initialized: true,
    counts: {
      ...workflowState.counts,
      projects: 1,
      workflows: 1,
      nodes: 7,
      edges: 6,
      audit_events: 2,
    },
    project_workflows: [
      {
        project_id: "project:offline-fixture-projects-codex-workbench",
        project_root: projectRoot,
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        title: "codex-workbench 默认工作流草稿",
        state: "draft",
        node_count: 7,
        edge_count: 6,
        task_draft_count: 2,
        task_drafts: [
          {
            work_item_id: "work-item:offline:001",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            title: "已有任务草稿",
            state: "ready_to_dispatch",
            assigned_role_id: "codex-dev",
            current_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:director",
            next_states: ["running", "paused"],
            next_action_label: "下一步：标记执行中",
            artifact_type: "task_package",
            artifact_path: null,
            recent_audit_events: [
              {
                event_id: "audit:offline:001",
                event_type: "task_draft_created",
                before_state: "missing_task_draft",
                after_state: "draft",
                created_at: "2026-05-29T00:00:00Z",
                reason: "离线夹具登记工作项",
              },
            ],
          },
          {
            work_item_id: "work-item:offline:002",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            title: "第二个任务草稿",
            state: "ready_for_review",
            assigned_role_id: "desktop-app",
            current_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:review",
            next_states: ["accepted", "needs_changes", "paused"],
            next_action_label: "下一步：接受或要求修改",
            artifact_type: "task_package",
            artifact_path: null,
            recent_audit_events: [],
          },
        ],
        director_reviews: [],
        node_session_bindings: [
          {
            binding_id: "binding:offline:codex-dev",
            project_id: "project:offline-fixture-projects-codex-workbench",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
            work_item_id: "work-item:offline:001",
            agent_type: "codex",
            adapter_id: "codex-local",
            native_thread_id: session.thread_id,
            native_rollout_path: session.rollout_path,
            session_title: session.title,
            session_updated_at_ms: session.updated_at_ms,
            rollout_exists: session.rollout_exists,
            project_binding_source: "index_inferred",
            binding_source: "workflow_bound",
            binding_mode: "select_existing_session",
            lifecycle: "active",
            created_at_ms: 1_764_000_000_000,
            updated_at_ms: 1_764_000_000_000,
            warnings: [],
          },
        ],
        node_dispatches: [
          {
            dispatch_id: "dispatch:offline:001",
            project_id: "project:offline-fixture-projects-codex-workbench",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
            work_item_id: "work-item:offline:001",
            binding_id: "binding:offline:codex-dev",
            native_thread_id: session.thread_id,
            prompt_preview: "请只回复这一句：WORKFLOW_NODE_DISPATCH_OK_2026_05_29",
            prompt_kind: "safe_probe",
            state: "completed",
            started_at_ms: 1_764_000_000_000,
            ended_at_ms: 1_764_000_001_000,
            exit_code: 0,
            last_message_path: "/tmp/codex-workflow-node-dispatch-v1/offline-last-message.txt",
            last_message_summary: "WORKFLOW_NODE_DISPATCH_OK_2026_05_29",
            transcript_event_count: 12,
            transcript_target_hits: 1,
            warnings: ["session_cwd_differs_from_project_root"],
          },
          {
            dispatch_id: "dispatch:offline:002",
            project_id: "project:offline-fixture-projects-codex-workbench",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
            work_item_id: "work-item:offline:002",
            binding_id: "binding:offline:codex-dev",
            native_thread_id: session.thread_id,
            prompt_preview: "请只回复这一句：WORKFLOW_NODE_DISPATCH_OK_2026_05_29",
            prompt_kind: "safe_probe",
            state: "completed",
            started_at_ms: 1_764_000_002_000,
            ended_at_ms: 1_764_000_003_000,
            exit_code: 0,
            last_message_path: "/tmp/codex-workflow-node-dispatch-v1/offline-last-message-002.txt",
            last_message_summary: "WORKFLOW_NODE_DISPATCH_OK_2026_05_29",
            transcript_event_count: 32,
            transcript_target_hits: 4,
            warnings: ["session_cwd_differs_from_project_root", "transcript_warning_count:3"],
          },
        ],
        execution_controls: [
          {
            control_id: "control:offline:001",
            project_id: "project:offline-fixture-projects-codex-workbench",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            work_item_id: "work-item:offline:001",
            control_state: "waiting_for_permission",
            long_task_state: "waiting_for_permission",
            retry_count: 1,
            max_retries: 0,
            timeout_seconds: 900,
            cancel_requested_at: null,
            failure_reason: "需要用户确认写入边界。",
            user_reviewed_instruction: {
              instruction_id: "instruction:offline:001",
              summary: "用户审核业务指令夹具",
              objective: "验证协议预览，不执行真实业务任务。",
              execution_cwd: "/Users/yoyi",
              sandbox_mode: "workspace-write",
              allowed_write_roots: ["/Users/yoyi/codex-workflow-mario-test"],
              allowed_reads: [projectRoot],
              allowed_writes: ["/Users/yoyi/codex-workflow-mario-test/index.html"],
              forbidden_actions: ["不读取 auth.json、.env、密钥、token 或授权文件", "不读取完整会话记录", "不运行运行器"],
              required_return: ["薄弱点", "验证命令和结果"],
              timeout_seconds: 900,
              max_retries: 0,
              approval_state: "reviewed",
              preview_markdown:
                "# 用户审核业务指令预览\n\n## 摘要\n用户审核业务指令夹具\n\n## 目标\n验证协议预览，不执行真实业务任务。\n\n## 执行目录\n/Users/yoyi\n\n## 沙箱模式\nworkspace-write",
            },
            audit_event_types: [
              "workflow_execution_control_defined",
              "workflow_permission_requested",
              "workflow_permission_decision_recorded",
              "workflow_execution_retry_scheduled",
              "workflow_execution_timeout_recorded",
              "workflow_execution_cancel_requested",
            ],
            warnings: ["protocol_only_not_business_execution"],
          },
        ],
        permission_requests: [
          {
            request_id: "permission:offline:001",
            project_id: "project:offline-fixture-projects-codex-workbench",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            work_item_id: "work-item:offline:001",
            dispatch_id: "dispatch:offline:001",
            permission_kind: "write_workflow_state",
            reason: "需要用户确认是否允许写协议字段。",
            status: "pending",
            requested_at: "2026-05-30T00:00:00Z",
            decided_at: null,
            decision: null,
            warnings: [],
          },
        ],
        execution_attempts: [
          {
            attempt_id: "attempt:offline:001",
            project_id: "project:offline-fixture-projects-codex-workbench",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            work_item_id: "work-item:offline:001",
            dispatch_id: "dispatch:offline:001",
            attempt_no: 1,
            state: "failed",
            started_at: "2026-05-30T00:00:00Z",
            ended_at: "2026-05-30T00:01:00Z",
            failure_reason: "离线夹具失败原因。",
            retry_scheduled_at: "2026-05-30T00:02:00Z",
            timed_out_at: null,
            cancel_requested_at: null,
            warnings: ["retry_pending_fixture"],
          },
          {
            attempt_id: "attempt:offline:002",
            project_id: "project:offline-fixture-projects-codex-workbench",
            workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
            work_item_id: "work-item:offline:001",
            dispatch_id: "dispatch:offline:001",
            attempt_no: 2,
            state: "timed_out",
            started_at: "2026-05-30T00:02:00Z",
            ended_at: "2026-05-30T00:17:00Z",
            failure_reason: "离线夹具超时。",
            retry_scheduled_at: null,
            timed_out_at: "2026-05-30T00:17:00Z",
            cancel_requested_at: "2026-05-30T00:18:00Z",
            warnings: ["cancel_requested_fixture"],
          },
        ],
      },
    ],
    warnings: ["状态文件已读取；只展示元数据，不展示正文。"],
  };

  return {
    workflowState,
    workflowStateWithProjectWorkflow,
  };
}
