import type { WorkflowStateSnapshot } from "../../src/lib/types";

type ProjectWorkflowFixture = NonNullable<WorkflowStateSnapshot["project_workflows"]>[number];
type DerivedWorkflowFixture = NonNullable<ProjectWorkflowFixture["derived_workflow"]>;
type ResultSummaryFixture = NonNullable<DerivedWorkflowFixture["result_summary"]>;

interface DerivedProjectWorkflowFixtureInput {
  projectRoot: string;
  sessionThreadId: string;
  workflowProjectId: string;
  workflowId: string;
}

export function derivedProjectWorkflowFixture(input: DerivedProjectWorkflowFixtureInput) {
  const { projectRoot, sessionThreadId, workflowProjectId, workflowId } = input;

  const pendingWorkflowResultSummary: ResultSummaryFixture = {
    project_id: workflowProjectId,
    workflow_id: workflowId,
    final_review_status: "pending",
    final_review_id: null,
    user_decision_status: "pending",
    user_decision_id: null,
    stage_c_acceptance: {
      project_id: workflowProjectId,
      workflow_id: workflowId,
      gates: [
        {
          gate_id: "c6-global-final-review",
          label: "C6 全局最终复核",
          status: "missing_evidence",
          reason: "全局主管尚未记录最终复核。",
          evidence_refs: [],
        },
        {
          gate_id: "stage-c-deferred-real-worker",
          label: "后置：真实工作者 / Codex 执行",
          status: "deferred",
          reason: "C6 默认不执行真实工作者、codex exec 或 codex exec resume。",
          evidence_refs: [],
        },
      ],
      final_review_status: "pending",
      user_decision_status: "pending",
      accepted_as_stage_c_complete: false,
      deferred_items: ["真实工作者 / Codex 执行仍需单独授权任务包。"],
      open_blockers: ["C6 全局最终复核：全局主管尚未记录最终复核。"],
      warnings: ["stage_c_acceptance_does_not_complete_middle_version", "process_fact_observation_is_not_formal_memory"],
    },
    open_issues: [],
    deferred_items: ["真实工作者 / Codex 执行仍需单独授权任务包。"],
    warnings: ["stage_c_acceptance_does_not_complete_middle_version", "process_fact_observation_is_not_formal_memory"],
  };

  const derivedWorkflow: DerivedWorkflowFixture = {
    workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
    project_id: "project:offline-fixture-projects-codex-workbench",
    title: "codex-workbench 默认工作流草稿",
    source_proposal_id: null,
    status: "draft",
    view_mode: null,
    created_by_role: "project_director",
    owner_role: "director",
    current_stage: "draft",
    run_check_status: "blocked",
    risk_level: null,
    result_summary: pendingWorkflowResultSummary,
    created_at: "2026-05-29T00:00:00Z",
    updated_at: "2026-05-29T00:00:00Z",
    nodes: [
      {
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        node_type: "agent",
        title: "Codex 开发线",
        assigned_role: "codex-dev",
        assigned_session_id: sessionThreadId,
        status: "draft",
        task_package_id: "artifact:offline:task-package:001",
        depends_on: ["workflow:offline-fixture-projects-codex-workbench:default:node:director"],
        harness_requirements: [],
        review_requirements: [],
        acceptance_criteria: [],
        created_at: null,
        updated_at: null,
        missing_fields: ["acceptance_criteria"],
        warnings: [],
      },
    ],
    task_packages: [
      {
        task_package_id: "artifact:offline:task-package:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:director",
        project_id: "project:offline-fixture-projects-codex-workbench",
        target_session_id: sessionThreadId,
        target_role: "codex-dev",
        task_goal: "已有任务草稿",
        allowed_read_scope: [projectRoot],
        allowed_write_scope: [],
        available_skills: ["offline-skill"],
        available_knowledge_refs: [],
        available_memory_refs: ["mem:formal:offline:included"],
        callable_tool_capabilities: [],
        model_id: null,
        harness_requirements: [],
        forbidden_actions: ["不读取 auth/token/.env/完整会话记录"],
        acceptance_criteria: [],
        report_format: [],
        timeout_policy: "未登记",
        failure_policy: "未登记",
        version: 2,
        stale: true,
        stale_reasons: ["manual_edit_requires_recheck"],
        missing_fields: ["allowed_write_scope", "model_id", "acceptance_criteria", "report_format"],
        export_includes_internal_audit: false,
        memory_injection_summary: {
          snapshot_id: "task-package-memory-packet-snapshot:v1:offline:001",
          included_count: 1,
          excluded_count: 2,
          review_material_count: 2,
          stale: false,
          stale_reasons: [],
          display_text:
            "任务包记忆注入摘要：入选 1 / 排除 2 / 待审查材料 2；快照新鲜。仅活跃正式记忆可进入任务包；候选 / 观察仅作为待审查材料；任务包内容不会回灌成正式记忆。",
          warnings: ["candidate_and_observation_review_materials_only"],
        },
        warnings: [],
      },
    ],
    ledger_entries: [
      {
        ledger_entry_id: "audit:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:director",
        entry_type: "task_package_created",
        actor_role: "project_director",
        actor_session_id: null,
        summary: "离线夹具登记工作项",
        source_refs: ["work-item:offline:001"],
        tool_call_refs: [],
        audit_refs: ["audit:offline:001"],
        risk_flags: [],
        created_at: "2026-05-29T00:00:00Z",
      },
      {
        ledger_entry_id: "ledger:dispatch:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        entry_type: "subagent_started",
        actor_role: "project_director",
        actor_session_id: sessionThreadId,
        summary: "请只回复这一句：WORKFLOW_NODE_DISPATCH_OK_2026_05_29",
        source_refs: ["work-item:offline:001"],
        tool_call_refs: [],
        audit_refs: [],
        risk_flags: ["session_cwd_differs_from_project_root"],
        created_at: "1764000000000",
      },
      {
        ledger_entry_id: "ledger:permission:permission:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: null,
        entry_type: "permission_requested",
        actor_role: "subagent_or_project_director",
        actor_session_id: null,
        summary: "需要用户确认是否允许写协议字段。",
        source_refs: ["work-item:offline:001"],
        tool_call_refs: [],
        audit_refs: [],
        risk_flags: [],
        created_at: "2026-05-30T00:00:00Z",
      },
      {
        ledger_entry_id: "ledger:tool:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        entry_type: "tool_call_summary",
        actor_role: "codex-dev",
        actor_session_id: sessionThreadId,
        summary: "工具调用只保留摘要和引用，不保留完整输出。",
        source_refs: ["work-item:offline:001"],
        tool_call_refs: ["tool-call:offline:001"],
        audit_refs: ["audit:offline:tool:001"],
        risk_flags: [],
        created_at: "2026-05-30T00:02:00Z",
      },
      {
        ledger_entry_id: "ledger:review:review:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:review",
        entry_type: "review_result",
        actor_role: "review",
        actor_session_id: null,
        summary: "审查通过，但节点仍需项目主管确认。",
        source_refs: ["work-item:offline:001"],
        tool_call_refs: [],
        audit_refs: ["audit:offline:review:001"],
        risk_flags: [],
        created_at: "2026-05-30T00:03:00Z",
      },
    ],
    subagent_reports: [
      {
        report_id: "report:dispatch:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        actor_role: "codex-dev",
        executed_what: "执行离线 safe probe。",
        changed_what: "没有写真实业务项目。",
        summary: "离线桩结果：已接收任务，没有执行真实 Codex 会话。",
        evidence_refs: ["evidence:offline:subagent:001"],
        open_issues: ["需要项目主管判断方向风险。"],
        permission_requests: ["permission:offline:001"],
        direction_risks: ["direction_risk_fixture"],
        follow_up_suggestions: ["由项目主管发起 proposal / decision request。"],
        acceptance_status: "reported_not_completed",
        warnings: ["subagent_cannot_complete_node"],
      },
    ],
    review_results: [
      {
        review_id: "review:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:review",
        result: "passed",
        summary: "审查通过，但 passed 不等于 completed。",
        evidence_refs: ["evidence:offline:review:001"],
        accepted_fact_ids: [],
        observation_ids: [],
        requires_director_confirmation: true,
        can_complete_node: false,
        warnings: ["review_passed_but_director_still_confirms_node_completion"],
      },
    ],
    exceptions: [
      {
        exception_id: "exception:permission:permission:offline:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: null,
        exception_type: "long_permission_wait",
        summary: "权限请求仍在等待。",
        status: "open",
        warnings: [],
      },
      {
        exception_id: "exception:direction:artifact:offline:task-package:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        exception_type: "unresolved_direction_risk",
        summary: "存在未解决方向风险；进入 waiting_decision，不自动继续。",
        status: "waiting_decision",
        warnings: ["direction_risk_fixture"],
      },
      {
        exception_id: "exception:harness:artifact:offline:task-package:001",
        workflow_id: "workflow:offline-fixture-projects-codex-workbench:default",
        workflow_node_id: "workflow:offline-fixture-projects-codex-workbench:default:node:codex-dev",
        exception_type: "harness_blocked",
        summary: "harness 阻断完成判定。",
        status: "open",
        warnings: ["harness_fixture"],
      },
    ],
    interface_boundaries: {
      proposal_interface: {
        interface_id: "proposal_interface",
        status: "conservative_stub",
        allowed: ["explicit_proposal_refs", "director_decision_request"],
        blocked: ["subagent_direct_user_decision", "implicit_direction_change"],
        source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
        warnings: [],
      },
      memory_candidate_interface: {
        interface_id: "memory_candidate_interface",
        status: "conservative_stub",
        allowed: ["confirmed_memory_refs", "memory_candidates_after_director_summary"],
        blocked: ["auto_write_formal_memory"],
        source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
        warnings: [],
      },
      knowledge_refs_interface: {
        interface_id: "knowledge_refs_interface",
        status: "conservative_stub",
        allowed: ["explicit_material_refs"],
        blocked: ["auto_scan_knowledge_base", "obsidian_native_without_design"],
        source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
        warnings: [],
      },
      tool_capability_registry: {
        interface_id: "tool_capability_registry",
        status: "conservative_stub",
        allowed: ["static_whitelist", "registered_tool_capabilities"],
        blocked: ["tool_without_whitelist", "tool_output_fulltext_in_ledger"],
        source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
        warnings: [],
      },
      model_pool_selector: {
        interface_id: "model_pool_selector",
        status: "conservative_stub",
        allowed: ["explicit_model_id"],
        blocked: ["silent_auto_model_selection"],
        source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
        warnings: [],
      },
      harness_requirement_provider: {
        interface_id: "harness_requirement_provider",
        status: "conservative_stub",
        allowed: ["run_check", "task_package_template", "completion_gate"],
        blocked: ["ordinary_workflow_node", "auto_run_harness"],
        source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
        warnings: [],
      },
      audit_refs_interface: {
        interface_id: "audit_refs_interface",
        status: "conservative_stub",
        allowed: ["summary_refs", "evidence_refs", "handoff_refs"],
        blocked: ["full_tool_output_in_workflow_ledger"],
        source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
        warnings: [],
      },
      warnings: [
        "multiple_harness_conflict_policy_open",
        "harness_failure_policy_open",
        "harness_output_ui_detail_open",
        "tool_call_summary_retention_granularity_open",
      ],
    },
    state_machine: {
      workflow_allowed_transitions: [
        "draft->ready",
        "ready->running",
        "running->paused",
        "paused->running",
        "running->waiting_decision",
        "waiting_decision->running",
        "running->completed",
        "running->failed",
        "completed->archived",
        "failed->archived",
      ],
      workflow_rejected_transitions: [
        "draft->running",
        "waiting_decision->completed",
        "failed->running_without_retry_or_reopen",
      ],
      node_allowed_transitions: [
        "not_started->waiting",
        "waiting->running",
        "running->waiting_permission",
        "waiting_permission->running",
        "running->waiting_decision",
        "waiting_decision->running",
        "running->reviewing",
        "reviewing->passed",
        "reviewing->returned",
        "returned->running",
        "running->failed",
        "running->paused",
        "paused->running",
        "waiting->skipped",
      ],
      node_rejected_transitions: [
        "subagent->passed",
        "waiting_decision->running_without_director",
        "failed->running_without_retry_or_reopen",
      ],
      completion_gate: {
        can_complete: false,
        required: [
          "task_goal_completed",
          "acceptance_criteria_met",
          "evidence_refs_exist",
          "review_or_harness_passed_when_required",
          "no_unresolved_risk",
          "memory_candidate_step_recorded",
          "final_user_report_need_recorded",
        ],
        missing: [
          "acceptance_criteria_met",
          "final_user_report_need_recorded",
          "memory_candidate_step_recorded",
          "no_unresolved_risk",
        ],
        warnings: ["only_project_director_can_mark_complete", "passed_not_equal_completed"],
      },
      warnings: [
        "passed_not_equal_completed",
        "subagent_and_review_agent_cannot_complete_node",
        "waiting_decision_requires_manual_confirmation",
      ],
    },
    acceptance_scenarios: [
      {
        scenario_id: "10.1",
        title: "子智能体发现方向风险",
        status: "covered_by_fixture",
        expected: [
          "subagent_report_writes_direction_risk",
          "node_enters_waiting_decision",
          "subagent_does_not_ask_user_directly",
        ],
        evidence_refs: ["exception:direction:artifact:offline:task-package:001"],
        warnings: [],
      },
      {
        scenario_id: "10.2",
        title: "任务包限制上下文",
        status: "blocked_until_package_complete",
        expected: [
          "explicit_memory_refs",
          "explicit_knowledge_refs",
          "explicit_tool_capabilities",
          "missing_scope_means_not_allowed",
        ],
        evidence_refs: ["artifact:offline:task-package:001"],
        warnings: [],
      },
      {
        scenario_id: "10.3",
        title: "子智能体完成并汇报",
        status: "covered_by_fixture",
        expected: [
          "report_enters_workflow_ledger",
          "memory_candidate_can_be_generated",
          "formal_memory_not_written_automatically",
        ],
        evidence_refs: ["report:dispatch:offline:001"],
        warnings: [],
      },
      {
        scenario_id: "10.4",
        title: "审查智能体通过",
        status: "covered_by_fixture",
        expected: ["review_result_stored", "project_director_still_marks_node_completion"],
        evidence_refs: ["review:offline:001"],
        warnings: [],
      },
      {
        scenario_id: "10.5",
        title: "harness 不是普通节点",
        status: "covered_by_rules",
        expected: [
          "harness_affects_run_check",
          "harness_affects_task_package_template",
          "harness_affects_completion_gate",
          "harness_not_main_workflow_node",
        ],
        evidence_refs: ["workflow_interface_boundaries.harness_requirement_provider"],
        warnings: [],
      },
    ],
    warnings: ["derived_from_workflow_state_v0_missing_fields_are_not_guessed"],
  };

  return {
    pendingWorkflowResultSummary,
    derivedWorkflow,
  };
}
