export const memoryKnowledgeTextFixtures = {
  // 候选治理 strip（含工作流观察展示）已从项目工作流侧栏删除（UI 删除任务）；
  // 这些正向文案断言整段移除。observationWorkflowForbiddenTexts 反向断言保留。
  observationWorkflowExpectedTexts: [] as string[],
  observationWorkflowForbiddenTexts: ["系统已记住", "自动学习完成", "observation 已成为正式记忆", "已注入任务包"],
  formalMemorySummaryForbiddenTexts: [
    "AI 自动记住",
    "候选已记住",
    "秘书已批准",
    "worker 已写入正式记忆",
    "完整记忆层完成",
    "系统已学习",
    "任务包注入已完成",
    "正式记忆完整完成",
  ],
  memoryLintSummaryExpectedTexts: [
    "记忆 lint 阻断摘要",
    "blocking finding 会阻止进入任务包",
    "lint 只生成待处理 finding",
    "不会自动修改正式记忆",
  ],
  taskPackageMemoryInjectionSummaryExpectedTexts: [
    "任务包记忆注入摘要",
    "仅活跃正式记忆可进入任务包",
    "候选 / 观察仅作为待审查材料",
    "任务包内容不会回灌成正式记忆",
  ],
  // 候选治理 strip（任务记忆包预览 / lint 阻断摘要等）已从项目工作流侧栏删除（UI 删除任务）；
  // 只保留仍由其它组件（节点详情记忆包段 / 任务包记忆注入摘要 read model）渲染的文案，删掉随 strip 消失的断言。
  taskMemoryPacketWorkflowExpectedTexts: [],
  taskMemoryPacketWorkflowForbiddenTexts: [
    "系统已记住",
    "自动学习完成",
    "候选已进入任务包",
    "observation 已注入任务包",
    "worker 已收到记忆包",
    "真实 worker 已执行",
    "系统已自动记住",
    "任务包内容已写入正式记忆",
    "任务包注入已完成",
    "中间版本记忆层完成",
    "AI 已自动解决冲突",
    "系统已废弃旧记忆",
    "旧记忆已自动更新",
    "正式记忆生命周期完成",
  ],
  memoryCenterExpectedTexts: [
    "记忆层",
    "AI 记着什么，你说了算",
    "候选 · 等你确认",
    "要你看",
    "正式 · 按项目",
    "正式 · 全局",
    "更多治理",
    "条候选等确认",
    "条要你看",
    "出方案会带上",
    "候选需要确认要求和风险提示。",
    "哪来的",
    "候选边界",
  ],
  memoryCenterForbiddenTexts: [
    "已记住",
    "系统已长期记住",
    "候选已成为正式记忆",
    "观察已成为正式记忆",
    "worker 已收到记忆包",
    "中间版本记忆层已完成",
    "编辑正式记忆",
    "删除正式记忆",
    "归档正式记忆",
    "自动合并实体",
    "自动确认关系",
    "图谱已证明",
    "LLM 已确认关系",
    "相似度已合并实体",
    "GraphRAG 已接入",
    "关系候选已成为事实",
    "自动清理记忆",
    "自动修复记忆",
    "维护任务已改正式记忆",
    "成熟模式已自动成为规则",
    "自动成为技能",
    "自动成为全局规则",
    "自动写入全局记忆",
    "跨项目摘要已注入任务包",
    "聚类报告就是事实",
    "成熟模式已生效",
    "M13 已完成",
    "中间版本记忆系统最终验收完成",
  ],
  memoryCenterExpectedClasses: [
    "memory-center",
    "memwrap",
    "mlist",
    "mmain",
    "mhead-strip",
    "memory-list-group",
    "mrow",
    "memory-detail-card",
    "memory-governance-trigger",
  ],
  lifecycleDialogExpectedTexts: [
    "正式记忆 废弃",
    "formal-memories.v1.json",
    "确认权",
    "project_director_or_user_confirmation",
    "影响 1 条正式记忆",
    "非活跃记忆默认不进任务包",
    "原版本 v1 / 新版本 v2",
    "会新增版本和审计",
  ],
  relationDialogExpectedTexts: [
    "确认关系候选",
    "memory-entity-relations.v1.json",
    "接口验收必须保留控制核心边界。",
    "接口契约资料",
    "已确认关系用于解释召回原因",
    "关系候选不会作为正式事实影响工作者",
  ],
  maintenanceDialogExpectedTexts: [
    "运行记忆维护任务",
    "memory-lint.v1.json",
    "维护运行",
    "维护任务只生成发现 / 报告",
    "阻断级发现会阻止召回",
    "不会自动修改正式记忆",
  ],
  maintenanceDialogForbiddenTexts: ["自动清理记忆", "自动修复记忆", "自动合并重复记忆", "维护任务已改正式记忆"],
  maturePatternDialogExpectedTexts: [
    "用户确认成熟模式候选",
    "memory-patterns.v1.json / formal-memories.v1.json",
    "跨项目重复边界：控制核心写入必须走确认",
    "用户确认写入正式记忆",
    "候选和跨项目主题报告未确认不进入任务包",
    "写版本、审计和来源引用",
    "只有用户确认正式化时才会联动 formal-memories.v1.json",
  ],
  maturePatternDialogForbiddenTexts: ["自动成为技能", "自动成为全局规则", "自动写入全局记忆", "跨项目摘要已注入任务包", "成熟模式已生效"],
  quarantineDialogExpectedTexts: [
    "隔离成熟模式候选",
    "memory-patterns.v1.json",
    "隔离候选",
    "未确认正式化",
    "候选和跨项目主题报告未确认不进入任务包",
  ],
  knowledgeViewExpectedTexts: [
    "知识库资料",
    "Obsidian-compatible 占位",
    "未执行 Obsidian 原生同步",
    "知识库是材料和笔记空间",
    "正式记忆是经过确认、来源、版本、审计和权限治理的行为上下文",
    "接口契约资料",
    "关联正式记忆 1",
    "关联候选 1",
    "任务包知识引用 1",
    "正式记忆引用了该知识库来源",
    "提出记忆候选",
    "只生成候选，不写正式记忆",
  ],
  knowledgeViewForbiddenTexts: [
    "已接入 Obsidian 原生同步",
    "vault 已自动扫描",
    "知识库已自动记住",
    "文档已成为正式记忆",
    "知识命中已成为正式记忆",
    "知识命中已注入任务包",
    "中间版本记忆层已完成",
  ],
  knowledgeCandidateDialogExpectedTexts: ["提出记忆候选", "memory-candidates.v1.json", "只生成候选，不写正式记忆", "knowledge_doc", "接口契约资料"],
  secretaryBriefExpectedTexts: ["秘书只读摘要", "需要你确认", "候选，不是正式记忆", "建议，不是事实变更"],
  secretaryBriefForbiddenTexts: ["秘书已处理", "秘书已执行", "已记住", "正式事实已写入"],
  secretaryPanelExpectedTexts: ["秘书只读摘要", "建议，不是事实变更", "候选，不是正式记忆", "秘书模型只读"],
  secretaryPanelForbiddenTexts: ["动态", "确认执行", "重新读取事实层"],
} as const;
