export const executionRunQueueTextFixtures = {
  agentConversationExpectedTexts: ["新对话", "搜索会话", "给 Codex", "发送"],
  // ⑥ H 定稿：开发者 11 面板从智能体页**退场**(定稿原话：「开发者 11 面板全部退场→审计账本页」)。
  // 这 11 个根 class 是它们的机械指纹——一个都不许再出现在智能体页 markup 里。
  //
  // ⚠️ 这条替换的是原来两处 `indexOf(a) < indexOf(b)` 的**排序断言**(「普通对话区必须排在开发者详情前面」)。
  // 那种写法在面板消失后是**哑弹**：indexOf 返回 -1 → `正数 < -1` 为 false → 断言照炸，但报错说「排序错了」，
  // 会把人往「顺序问题」的死胡同带。改成正向断言：面板就是不该在。
  agentRetiredDeveloperPanelMarkers: [
    "codex-control-panel",
    "unified-execution-panel",
    "adapter-capability-panel",
    "provider-availability-panel",
    "session-continuation-panel",
    "controlled-continuation-panel",
    "h2-resume-authorization-panel",
    "h2-execution-decision-panel",
    "runtime-attention-panel",
    "adapter-sdk-diagnostics-panel",
    "session-operation-panel",
  ],
  agentUnifiedExecutionExpectedTexts: [
    "统一执行链路",
    "2 条统一命令",
    "等待确认：1",
    "受控记录：1",
    "阻断：1",
    "读回边界：未知 / 不可用",
  ],
  agentAutomationExpectedTexts: [
    "自动编排：Level A 闭环已记录",
    "编排 run units：5",
    "编排读回未知：5",
    "编排捕获来源：1",
    "worker report 已回收",
  ],
  agentCodexControlExpectedTexts: [
    "Codex 控制",
    "J1-A · 产品命令入口 · 非真实执行",
    "生成预览",
    "写入准备",
    "用户确认",
    "记录 Phase A（不真实执行）",
    "任务正文保存策略",
    "观察 / 候选来源",
    "不会自动写正式记忆",
    "临时运行绑定",
  ],
  agentFailureBoundaryExpectedTexts: [
    "需要重新确认",
    "用户已拒绝",
    "被安全边界阻断",
    "被诊断阻断",
    "重复执行已阻断",
    "记忆包缺失或过期",
    "读回不可用",
    "读回失败",
    "执行超时",
    "运行失败",
    "停止请求需受控处理",
  ],
  runningUnifiedExecutionExpectedTexts: [
    "统一执行命令",
    "2",
    "1 等确认",
    "最近状态",
    "受控记录已写入",
    "不等于真实 Codex 自由运行",
    "未知 / 不可用不显示成 0",
  ],
  runningAutomationExpectedTexts: [
    "自动编排",
    "5",
    "0 等确认",
    "5 读回未知",
    "worker report",
    "捕获来源",
    "过程观察",
    "主管复核",
  ],
  runningFailureBoundaryExpectedTexts: [
    "失败",
    "读回异常",
    "停止请求",
    "需要重新确认",
    "读回结果：未知 / 不可用",
  ],
  projectDetailUnifiedExecutionExpectedTexts: [
    "主管复核",
  ],
  secretaryActionProposalForbiddenTexts: ["批准", "派发", "重试", "stop", "resume", "停止", "恢复"],
  rightRailUnifiedExecutionExpectedTexts: [
    "统一执行链路",
    "统一执行命令状态",
    "最近状态：受控记录已写入",
    "读回未知 / 不可用不能显示成 0",
  ],
  rightRailFailureExpectedTexts: [
    "失败",
    "读回异常",
    "需确认",
    "停止请求",
    "停止请求需受控处理",
    "读回结果：未知 / 不可用",
  ],
  combinedMarkupForbiddenTexts: [
    "H5 命令",
    "H6 真实执行状态",
    "允许一次",
    "结果数：0",
    "runRealExecutionProductCommandPhaseA",
    "runRealExecutionProductCommandPhaseB",
    "run_real_execution_product_command_phase_b",
    "confirmRealExecutionProductCommand",
    "recordRealExecutionProductCommandDecision",
    "prepareRealExecutionProductCommand",
  ],
  stageJRunningExpectedTexts: [
    "运行队列",
    "待确认",
    "失败控制",
    "操作控制 / 恢复建议",
    "重试提案",
    "停止请求",
    "重启准备",
    "恢复准备",
    "L3 决策面",
    "后续任务",
    "单独授权",
    "不会进入 real-resume phase B",
    "不扩大既有门",
    "重试确认",
    "停止 / 取消确认",
    "过程事实确认",
    "记忆候选确认",
    "正式化确认",
    "捕获补偿确认",
    "重复执行已阻断",
    "候选不是正式记忆",
    "结果数：未知 / 不可用",
    "不会自动调用运行器",
  ],
  l3OperationControlExpectedTexts: [
    "L3 决策面",
    "可发起确认",
    "需另窗授权",
    "无 runtime handle",
    "重启语义未冻结",
    "real-resume 门未放宽",
    "confirmed_recorded",
    "not_attempted_l3_decision_only",
    "operation_decision_recorded",
    "operation_decision_recorded_pending_real_authorization",
    "K3-B2 仍阻断",
    "确认记录 重试 决策",
    "确认记录 停止 决策",
    "确认记录 重启 决策",
    "确认记录 恢复 决策",
  ],
  l3OperationControlDialogExpectedTexts: [
    "本机动作确认",
    "L3 操作",
    "当前门",
    "确认后状态",
    "confirmed_recorded",
    "只登记决策",
    "读回：not_attempted_l3_decision_only；结果数：未知/不可用",
    "operation_decision_recorded",
    "operation_decision_recorded_pending_real_authorization",
    "确认记录决策",
    "不调用 runner",
    "不停止或重启真实进程",
  ],
  l3OperationControlForbiddenTexts: [
    "自动重试已启用",
    "已成功",
    "真实恢复已完成",
    "安全审查已绕过",
    "读回 0 条",
    "已获得通用真实执行授权",
    "K3-B2 可开始",
  ],
  stageJRightRailExpectedTexts: [
    "运行队列",
    "待确认",
    "失败控制",
    "捕获补偿",
    "不自动执行",
    "记忆候选确认",
    "正式化确认",
    "捕获补偿确认",
  ],
  stageJCombinedForbiddenTexts: [
    "自动重试中",
    "已自动修复",
    "已写正式记忆",
    "结果数：0",
    "runner_call",
    "codex exec resume",
    "已停止",
    "已重启",
    "已恢复",
    "已 resume",
  ],
} as const;
