import type {
  MemoryCandidateStoreV1,
  MemoryCaptureStoreV1,
  RuntimeSessionAttention,
  WorkbenchSnapshot,
  WorkflowStateSnapshot,
} from "../../src/lib/types";

interface StageJRunQueueFixtureInput {
  snapshot: WorkbenchSnapshot;
  workflowStateWithProjectWorkflow: WorkflowStateSnapshot;
  projectRoot: string;
}

export function stageJRunQueueFixtures(input: StageJRunQueueFixtureInput) {
  const { snapshot, workflowStateWithProjectWorkflow, projectRoot } = input;
  const j4FailureItems = [
    ["retry_requires_new_user_confirmation", "需要重新确认", "再次执行前需要新的用户确认；不会自动重试。", "high", true, ["product_command_retry_boundary"], ["pcr7_no_auto_retry_requires_new_user_confirmation"]],
    ["manual_stop_requested", "停止请求需受控处理", "用户请求停止仅作为产品状态，本任务不会停止真实进程。", "medium", false, ["decision:j4:manual_stop"], ["manual_stop_requested_from_decision_reason"]],
    ["duplicate_blocked", "重复执行已阻断", "已有重复命令或运行记录，不能并行继续。", "medium", false, ["preview:j4:duplicate"], ["duplicate_active"]],
    ["readback_failed", "读回失败", "读回尝试失败或不可信，结果数未知。", "high", true, ["attempt:j4:readback_failed"], ["readback_parser_failed"]],
    ["timed_out", "执行超时", "执行或读回超时，不能解释为已经完成停止。", "high", true, ["attempt:j4:timed_out"], ["readback_timed_out"]],
  ].map(([kind, title, summary, severity, requiresNewUserConfirmation, sourceRefs, warnings]) => ({
    kind: kind as string,
    title: title as string,
    summary: summary as string,
    count: 1,
    severity: severity as string,
    requires_new_user_confirmation: requiresNewUserConfirmation as boolean,
    result_count: null,
    source_refs: sourceRefs as string[],
    warnings: warnings as string[],
  }));
  const activeReadModel = {
    ...snapshot.real_execution_product_commands!,
    store_available: true,
    command_count: 3,
    pending_decision_count: 1,
    running_attempt_count: 1,
    blocked_attempt_count: 1,
    last_attempt_status: "readback_failed",
    failure_stop_retry_summary: {
      schema_version: "real_execution_product_command_failure_stop_retry.v1",
      item_count: j4FailureItems.length,
      failure_count: 2,
      blocked_count: 1,
      readback_issue_count: 2,
      manual_stop_requested_count: 1,
      retry_requires_new_user_confirmation: true,
      items: j4FailureItems,
      warnings: ["j4_failure_control_fixture"],
    },
    warnings: ["j4_readback_null_fixture"],
  };
  const workflowId = workflowStateWithProjectWorkflow.project_workflows[0]?.workflow_id ?? "workflow:j4:fixture";
  const activeAutomation = {
    schema_version: "project_workflow_automation.v1",
    available: true,
    generated_at: "2026-06-09T12:00:00Z",
    latest_automation_id: "j4-automation:offline",
    latest_status: "phase_a_closed_loop_recorded",
    latest_plan: {
      schema_version: "project_workflow_automation.v1",
      automation_id: "j4-automation:offline",
      project_id: "project:offline",
      project_root: projectRoot,
      workflow_id: workflowId,
      user_goal: "离线验证 J4 运行队列。",
      current_phase: "director_final_review",
      next_step: "等待用户处理 J4 待确认队列。",
      run_units: [
        {
          run_unit_id: "run-unit:j4:developer",
          run_unit_kind: "developer_execution",
          role: "developer_execution",
          status: "readback_unavailable",
          project_id: "project:offline",
          project_root: projectRoot,
          workflow_id: workflowId,
          workflow_node_id: `${workflowId}:node:codex-dev`,
          work_item_id: "work-item:j4:developer",
          task_package_ref: "task-package:j4",
          memory_packet_ref: "memory-packet:j4",
          product_command_preview_ref: "preview:j4:developer",
          product_command_ref: "product-command:j4:developer",
          runtime_log_refs: ["runtime-log:j4:developer"],
          audit_refs: ["audit:j4:developer"],
          readback_ref: "readback:j4:developer",
          readback_status: "readback_unavailable",
          readback_result_count: null,
          worker_report_ref: null,
          capture_event_refs: ["capture:j4:compensation"],
          observation_refs: [],
          memory_candidate_refs: [],
          runner_call_allowed: false,
          prompt_sent: false,
          real_codex_executed: false,
          writes_codex_home: false,
          writes_project_files: false,
          summary: "开发线读回不可用，结果数未知。",
          next_step: "等待人工查看读回边界。",
          blocked_reasons: [],
          warnings: ["unknown_readback_result_count_must_remain_null"],
        },
        {
          run_unit_id: "run-unit:j4:collector",
          run_unit_kind: "collector_summary",
          role: "collector_summary",
          status: "completed",
          project_id: "project:offline",
          project_root: projectRoot,
          workflow_id: workflowId,
          workflow_node_id: `${workflowId}:node:collector`,
          work_item_id: "work-item:j4:collector",
          task_package_ref: "task-package:j4",
          memory_packet_ref: "memory-packet:j4",
          product_command_preview_ref: null,
          product_command_ref: null,
          runtime_log_refs: ["runtime-log:j4:collector"],
          audit_refs: ["audit:j4:collector"],
          readback_ref: null,
          readback_status: "unknown",
          readback_result_count: null,
          worker_report_ref: "worker-report:j4",
          capture_event_refs: ["capture:j4:candidate"],
          observation_refs: ["observation:j4:collector"],
          memory_candidate_refs: [],
          runner_call_allowed: false,
          prompt_sent: false,
          real_codex_executed: false,
          writes_codex_home: false,
          writes_project_files: false,
          summary: "回收线已形成观察。",
          next_step: "等待主管复核。",
          blocked_reasons: [],
          warnings: [],
        },
        {
          run_unit_id: "run-unit:j4:review",
          run_unit_kind: "director_final_review",
          role: "global_director",
          status: "needs_review",
          project_id: "project:offline",
          project_root: projectRoot,
          workflow_id: workflowId,
          workflow_node_id: `${workflowId}:node:review`,
          work_item_id: "work-item:j4:review",
          task_package_ref: "task-package:j4",
          memory_packet_ref: "memory-packet:j4",
          product_command_preview_ref: null,
          product_command_ref: null,
          runtime_log_refs: [],
          audit_refs: ["audit:j4:review"],
          readback_ref: null,
          readback_status: "unknown",
          readback_result_count: null,
          worker_report_ref: "worker-report:j4",
          capture_event_refs: [],
          observation_refs: [],
          memory_candidate_refs: [],
          runner_call_allowed: false,
          prompt_sent: false,
          real_codex_executed: false,
          writes_codex_home: false,
          writes_project_files: false,
          summary: "主管复核等待确认。",
          next_step: "确认过程事实。",
          blocked_reasons: [],
          warnings: [],
        },
      ],
      blocked_reasons: [],
      warnings: ["j4_queue_fixture"],
    },
    run_unit_count: 3,
    waiting_user_count: 1,
    blocked_count: 0,
    readback_unknown_count: 3,
    worker_report_count: 2,
    capture_event_count: 2,
    observation_count: 1,
    next_step: "等待用户处理 J4 待确认队列。",
    warnings: ["j4_run_queue_fixture"],
  };
  const memoryCaptureStore: MemoryCaptureStoreV1 = {
    store_version: "memory_capture_store.v1",
    project_id: "project:offline",
    workflow_id: workflowId,
    revision: 2,
    events: [
      {
        capture_event_id: "capture:j4:candidate",
        event_key: "j4:candidate",
        schema_version: "memory_capture_event.v1",
        source_type: "worker_report",
        source_ref_id: "worker-report:j4",
        project_id: "project:offline",
        workflow_id: workflowId,
        workflow_node_id: `${workflowId}:node:collector`,
        run_unit_id: "run-unit:j4:collector",
        product_command_id: null,
        product_attempt_id: null,
        runtime_log_ref: "runtime-log:j4:collector",
        audit_refs: ["audit:j4:collector"],
        readback_ref: null,
        task_package_ref: "task-package:j4",
        memory_packet_ref: "memory-packet:j4",
        summary: "J4 运行事实可以形成候选。",
        evidence_summary: "离线 fixture。",
        sensitivity: "internal",
        candidate_policy: "candidate_allowed",
        blocked_reason: null,
        observation_id: "observation:j4:collector",
        candidate_key: "memory-candidate:j4:collector",
        created_by: "project_director",
        created_at: "2026-06-09T12:00:00Z",
        updated_at: "2026-06-09T12:00:00Z",
      },
      {
        capture_event_id: "capture:j4:compensation",
        event_key: "j4:compensation",
        schema_version: "memory_capture_event.v1",
        source_type: "readback",
        source_ref_id: "readback:j4:developer",
        project_id: "project:offline",
        workflow_id: workflowId,
        workflow_node_id: `${workflowId}:node:codex-dev`,
        run_unit_id: "run-unit:j4:developer",
        product_command_id: "product-command:j4:developer",
        product_attempt_id: "attempt:j4:developer",
        runtime_log_ref: "runtime-log:j4:developer",
        audit_refs: ["audit:j4:developer"],
        readback_ref: "readback:j4:developer",
        task_package_ref: "task-package:j4",
        memory_packet_ref: "memory-packet:j4",
        summary: "候选链路半完成。",
        evidence_summary: "离线 fixture。",
        sensitivity: "internal",
        candidate_policy: "candidate_allowed",
        blocked_reason: null,
        observation_id: null,
        candidate_key: null,
        created_by: "project_director",
        created_at: "2026-06-09T12:01:00Z",
        updated_at: "2026-06-09T12:01:00Z",
      },
    ],
    updated_at: "2026-06-09T12:01:00Z",
    warnings: [],
  };
  const memoryCandidateStore: MemoryCandidateStoreV1 = {
    store_version: "memory_candidate_store.v1",
    project_id: "project:offline",
    workflow_id: workflowId,
    revision: 1,
    candidates: [
      {
        candidate_id: "memcand:j4:formalization",
        candidate_key: "memcand:v1:j4-formalization",
        schema_version: "memory_governance.v1",
        scope: {
          scope_id: "scope:project:j4",
          scope_type: "project",
          project_id: "project:offline",
          workflow_id: workflowId,
          role_ids: [],
          document_refs: [],
          model_export_policy: "local_only",
          valid_from: "2026-06-09T12:00:00Z",
        },
        memory_type: "workflow_summary",
        claim: "J4 运行队列需要保留候选正式化边界。",
        body: "已确认候选仍不是正式记忆，需要继续走正式化生命周期。",
        source_refs: [
          {
            source_ref_id: "source:j4:formalization",
            source_type: "observation_ref",
            source_id: "capture:j4:candidate",
            source_title: "J4 capture candidate",
            captured_at: "2026-06-09T12:00:00Z",
            authority_level: "derived_summary",
            sensitive_level: "project",
          },
        ],
        generated_by_role: "project_director",
        generated_from: "observation:observation:j4:collector",
        status: "candidate_confirmed",
        risk_level: "medium",
        sensitive_level: "project",
        requires_user_confirmation: true,
        review_reason: "J4 正式化确认 fixture。",
        conflicts: [],
        audit_refs: [],
        adoption: null,
        created_at: "2026-06-09T12:00:00Z",
        updated_at: "2026-06-09T12:00:00Z",
      },
    ],
    events: [],
    updated_at: "2026-06-09T12:00:00Z",
  };
  const j4RuntimeAttention: RuntimeSessionAttention[] = [
    {
      attention_id: "attention:j4:readback-failed",
      project_id: "project:offline",
      workflow_id: workflowId,
      node_id: `${workflowId}:node:codex-dev`,
      session_id: "session:j4",
      adapter_id: "codex-local",
      source_refs: [{ source_kind: "runtime_log", source_id: "runtime-log:j4:readback", label: "读回日志" }],
      kind: "readback_failed",
      severity: "blocking",
      status: "readback_failed",
      title: "读回失败，等待人工处理",
      user_message: "读回失败不能当成 0 条结果。",
      technical_summary: "offline fixture",
      recommended_next_step: "查看运行队列和失败控制。",
      requires_user_action: true,
      blocks_continuation: true,
      readback_boundary: {
        status: "readback_failed",
        reason: "readback_parser_failed",
        attempted: true,
        real_readback_performed: false,
        result_count: null,
        user_message: "读回失败，结果数未知。",
        technical_summary: "offline fixture",
        source_refs: [{ source_kind: "runtime_log", source_id: "runtime-log:j4:readback", label: "读回日志" }],
        warnings: ["unknown_readback_result_count_must_remain_null"],
      },
      created_at: "2026-06-09T12:02:00Z",
      updated_at: "2026-06-09T12:02:00Z",
      warnings: [],
    },
  ];
  const j4Snapshot: WorkbenchSnapshot = {
    ...snapshot,
    runtime_session_attention: j4RuntimeAttention,
    real_execution_product_commands: activeReadModel,
    project_workflow_automation: activeAutomation,
  };

  return {
    activeAutomation,
    activeReadModel,
    j4RuntimeAttention,
    j4Snapshot,
    memoryCandidateStore,
    memoryCaptureStore,
    workflowId,
  };
}
