// 浏览器预览专用的工作流数据（纯数据常量，无 hook / 无副作用，SSR 安全）。
// 目的：让 `npm run dev` 普通浏览器预览（无 Tauri）下，项目工作流画布能渲染出节点、
// 右侧「项目咨询方案草案」显示一份待确认方案。
//
// 结构来源：离线测试夹具
//   - tests/helpers/offlineDerivedProjectWorkflowFixtures.ts（derived_workflow / nodes / task_packages 的真实形）
//   - tests/helpers/offlineProjectWorkflowStateFixtures.ts（project_workflow + task_drafts 的真实形）
//   - tests/helpers/offlineAuthorizationWorkflowClusterFixtures.ts（方案 / 授权 store 的真实形）
// 这里**不** import tests/（tests 不在 build 里），而是照夹具的真实字段重抄一份，
// 并把 project_root / project_id / workflow_id 改成预览项目的常量。
//
// 画布节点判据（src/lib/projectCanvas.ts deriveProjectWorkflowCanvasReadModel）：
//   画布按 derived_workflow.nodes 1:1 渲染；assigned_role 命中 director / codex-dev /
//   review（或 workflow_node_id == `${workflowId}:node:${role}`）→ 映射到固定泳道
//   （总指导 / 开发线 / 回收线）。这里放 3 个真实节点 → 画布出 3 个节点。
// 方案卡判据（src/lib/projectConsultationProposal.ts summarizeProjectConsultationProposalStore）：
//   按 proposal.project_id == workflow.project_id && proposal.workflow_id == workflow.workflow_id
//   过滤、取最后一条；status=pending_user_confirmation → 「待用户确认」。

import { previewProjectRoot } from "./browserPreviewSnapshot";
import type {
  PlanAuthorizationStoreV1,
  ProjectConsultationProposalStoreV1,
  Workflow,
  WorkflowStateSnapshot,
} from "./types";

const previewProjectId = "project:browser-preview-productized-desktop-shell";
const previewWorkflowId = "workflow:browser-preview-productized-desktop-shell:default";
const previewSessionThreadId = "browser-preview-thread-layout";

const directorNodeId = `${previewWorkflowId}:node:director`;
const devNodeId = `${previewWorkflowId}:node:codex-dev`;
const reviewNodeId = `${previewWorkflowId}:node:review`;

const directorWorkItemId = "work-item:browser-preview:director";
const devWorkItemId = "work-item:browser-preview:dev";
const reviewWorkItemId = "work-item:browser-preview:review";

const devTaskPackageId = "artifact:browser-preview:task-package:dev";

// derived_workflow：画布的真实节点来源。3 个节点（总指导 / 开发线 / 回收线）。
const previewDerivedWorkflow: Workflow = {
  workflow_id: previewWorkflowId,
  project_id: previewProjectId,
  title: "桌面壳预览工作流草稿",
  source_proposal_id: null,
  status: "draft",
  view_mode: null,
  created_by_role: "project_director",
  owner_role: "director",
  current_stage: "draft",
  run_check_status: "blocked",
  risk_level: null,
  created_at: "2026-06-19T10:00:00.000Z",
  updated_at: "2026-06-19T10:00:00.000Z",
  nodes: [
    {
      workflow_node_id: directorNodeId,
      workflow_id: previewWorkflowId,
      node_type: "director",
      title: "总指导",
      assigned_role: "director",
      assigned_session_id: previewSessionThreadId,
      status: "draft",
      task_package_id: null,
      depends_on: [],
      harness_requirements: [],
      review_requirements: [],
      acceptance_criteria: [],
      created_at: null,
      updated_at: null,
      missing_fields: [],
      warnings: [],
    },
    {
      workflow_node_id: devNodeId,
      workflow_id: previewWorkflowId,
      node_type: "agent",
      title: "开发线",
      assigned_role: "codex-dev",
      assigned_session_id: previewSessionThreadId,
      status: "draft",
      task_package_id: devTaskPackageId,
      depends_on: [directorNodeId],
      harness_requirements: [],
      review_requirements: [],
      acceptance_criteria: [],
      created_at: null,
      updated_at: null,
      missing_fields: ["acceptance_criteria"],
      warnings: [],
    },
    {
      workflow_node_id: reviewNodeId,
      workflow_id: previewWorkflowId,
      node_type: "review",
      title: "回收线",
      assigned_role: "review",
      assigned_session_id: null,
      status: "draft",
      task_package_id: null,
      depends_on: [devNodeId],
      harness_requirements: [],
      review_requirements: [],
      acceptance_criteria: [],
      created_at: null,
      updated_at: null,
      missing_fields: [],
      warnings: [],
    },
  ],
  task_packages: [
    {
      task_package_id: devTaskPackageId,
      workflow_id: previewWorkflowId,
      workflow_node_id: devNodeId,
      project_id: previewProjectId,
      target_session_id: previewSessionThreadId,
      target_role: "codex-dev",
      task_goal: "打磨桌面壳布局",
      allowed_read_scope: [previewProjectRoot],
      allowed_write_scope: [],
      available_skills: ["browser-preview-skill"],
      available_knowledge_refs: [],
      available_memory_refs: [],
      callable_tool_capabilities: [],
      model_id: null,
      harness_requirements: [],
      forbidden_actions: ["不读取 auth/token/.env/完整会话记录"],
      acceptance_criteria: [],
      report_format: [],
      timeout_policy: "未登记",
      failure_policy: "未登记",
      version: 1,
      stale: false,
      stale_reasons: [],
      missing_fields: ["allowed_write_scope", "model_id", "acceptance_criteria", "report_format"],
      export_includes_internal_audit: false,
      memory_injection_summary: {
        snapshot_id: "task-package-memory-packet-snapshot:v1:browser-preview:dev",
        included_count: 0,
        excluded_count: 0,
        review_material_count: 0,
        stale: false,
        stale_reasons: [],
        display_text:
          "任务包记忆注入摘要：入选 0 / 排除 0 / 待审查材料 0；快照新鲜。仅活跃正式记忆可进入任务包；候选 / 观察仅作为待审查材料；任务包内容不会回灌成正式记忆。",
        warnings: [],
      },
      warnings: [],
    },
  ],
  ledger_entries: [
    {
      ledger_entry_id: "ledger:browser-preview:task-package-created",
      workflow_id: previewWorkflowId,
      workflow_node_id: devNodeId,
      entry_type: "task_package_created",
      actor_role: "project_director",
      actor_session_id: null,
      summary: "浏览器预览示例：登记开发线任务包草稿。",
      source_refs: [devWorkItemId],
      tool_call_refs: [],
      audit_refs: [],
      risk_flags: [],
      created_at: "2026-06-19T10:00:00.000Z",
    },
  ],
  subagent_reports: [],
  review_results: [],
  exceptions: [],
  result_summary: {
    project_id: previewProjectId,
    workflow_id: previewWorkflowId,
    final_review_status: "pending",
    final_review_id: null,
    user_decision_status: "pending",
    user_decision_id: null,
    stage_c_acceptance: {
      project_id: previewProjectId,
      workflow_id: previewWorkflowId,
      gates: [
        {
          gate_id: "c6-global-final-review",
          label: "C6 全局最终复核",
          status: "missing_evidence",
          reason: "全局主管尚未记录最终复核。",
          evidence_refs: [],
        },
        {
          gate_id: "stage-c-deferred-real-worker",
          label: "后置：真实工作者 / Codex 执行",
          status: "deferred",
          reason: "C6 默认不执行真实工作者、codex exec 或 codex exec resume。",
          evidence_refs: [],
        },
      ],
      final_review_status: "pending",
      user_decision_status: "pending",
      accepted_as_stage_c_complete: false,
      deferred_items: ["真实工作者 / Codex 执行仍需单独授权任务包。"],
      open_blockers: ["C6 全局最终复核：全局主管尚未记录最终复核。"],
      warnings: ["stage_c_acceptance_does_not_complete_middle_version", "process_fact_observation_is_not_formal_memory"],
    },
    open_issues: [],
    deferred_items: ["真实工作者 / Codex 执行仍需单独授权任务包。"],
    warnings: ["stage_c_acceptance_does_not_complete_middle_version", "process_fact_observation_is_not_formal_memory"],
  },
  interface_boundaries: {
    proposal_interface: {
      interface_id: "proposal_interface",
      status: "conservative_stub",
      allowed: ["explicit_proposal_refs", "director_decision_request"],
      blocked: ["subagent_direct_user_decision", "implicit_direction_change"],
      source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
      warnings: [],
    },
    memory_candidate_interface: {
      interface_id: "memory_candidate_interface",
      status: "conservative_stub",
      allowed: ["confirmed_memory_refs", "memory_candidates_after_director_summary"],
      blocked: ["auto_write_formal_memory"],
      source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
      warnings: [],
    },
    knowledge_refs_interface: {
      interface_id: "knowledge_refs_interface",
      status: "conservative_stub",
      allowed: ["explicit_material_refs"],
      blocked: ["auto_scan_knowledge_base", "obsidian_native_without_design"],
      source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
      warnings: [],
    },
    tool_capability_registry: {
      interface_id: "tool_capability_registry",
      status: "conservative_stub",
      allowed: ["static_whitelist", "registered_tool_capabilities"],
      blocked: ["tool_without_whitelist", "tool_output_fulltext_in_ledger"],
      source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
      warnings: [],
    },
    model_pool_selector: {
      interface_id: "model_pool_selector",
      status: "conservative_stub",
      allowed: ["explicit_model_id"],
      blocked: ["silent_auto_model_selection"],
      source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
      warnings: [],
    },
    harness_requirement_provider: {
      interface_id: "harness_requirement_provider",
      status: "conservative_stub",
      allowed: ["run_check", "task_package_template", "completion_gate"],
      blocked: ["ordinary_workflow_node", "auto_run_harness"],
      source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
      warnings: [],
    },
    audit_refs_interface: {
      interface_id: "audit_refs_interface",
      status: "conservative_stub",
      allowed: ["summary_refs", "evidence_refs", "handoff_refs"],
      blocked: ["full_tool_output_in_workflow_ledger"],
      source_refs: ["workflow-task-package-design-v1-confirmed-boundary"],
      warnings: [],
    },
    warnings: [
      "multiple_harness_conflict_policy_open",
      "harness_failure_policy_open",
      "harness_output_ui_detail_open",
      "tool_call_summary_retention_granularity_open",
    ],
  },
  state_machine: {
    workflow_allowed_transitions: [
      "draft->ready",
      "ready->running",
      "running->paused",
      "paused->running",
      "running->waiting_decision",
      "waiting_decision->running",
      "running->completed",
      "running->failed",
      "completed->archived",
      "failed->archived",
    ],
    workflow_rejected_transitions: [
      "draft->running",
      "waiting_decision->completed",
      "failed->running_without_retry_or_reopen",
    ],
    node_allowed_transitions: [
      "not_started->waiting",
      "waiting->running",
      "running->waiting_permission",
      "waiting_permission->running",
      "running->waiting_decision",
      "waiting_decision->running",
      "running->reviewing",
      "reviewing->passed",
      "reviewing->returned",
      "returned->running",
      "running->failed",
      "running->paused",
      "paused->running",
      "waiting->skipped",
    ],
    node_rejected_transitions: [
      "subagent->passed",
      "waiting_decision->running_without_director",
      "failed->running_without_retry_or_reopen",
    ],
    completion_gate: {
      can_complete: false,
      required: [
        "task_goal_completed",
        "acceptance_criteria_met",
        "evidence_refs_exist",
        "review_or_harness_passed_when_required",
        "no_unresolved_risk",
        "memory_candidate_step_recorded",
        "final_user_report_need_recorded",
      ],
      missing: [
        "acceptance_criteria_met",
        "final_user_report_need_recorded",
        "memory_candidate_step_recorded",
        "no_unresolved_risk",
      ],
      warnings: ["only_project_director_can_mark_complete", "passed_not_equal_completed"],
    },
    warnings: [
      "passed_not_equal_completed",
      "subagent_and_review_agent_cannot_complete_node",
      "waiting_decision_requires_manual_confirmation",
    ],
  },
  acceptance_scenarios: [],
  warnings: ["derived_from_workflow_state_v0_missing_fields_are_not_guessed"],
};

export const browserPreviewWorkflowState: WorkflowStateSnapshot = {
  exists: true,
  path: "/browser-preview/Application Support/CodexGovernanceWorkbench/workflow-state/workflow-state.v0.json",
  schema_version: "workflow_state_v0",
  workflow_version: 1,
  workspace_id: null,
  updated_at: "2026-06-19T10:00:00.000Z",
  initialized: true,
  counts: {
    projects: 1,
    agent_adapters: 0,
    workflows: 1,
    nodes: 3,
    edges: 2,
    work_items: 3,
    artifacts: 1,
    reviews: 0,
    audit_events: 1,
    capabilities: 0,
    harness_resources: 0,
  },
  project_workflows: [
    {
      project_id: previewProjectId,
      project_root: previewProjectRoot,
      workflow_id: previewWorkflowId,
      title: "桌面壳预览工作流草稿",
      state: "draft",
      node_count: 3,
      edge_count: 2,
      task_draft_count: 3,
      task_drafts: [
        {
          work_item_id: devWorkItemId,
          workflow_id: previewWorkflowId,
          title: "打磨桌面壳布局",
          state: "ready_to_dispatch",
          assigned_role_id: "codex-dev",
          current_node_id: devNodeId,
          next_states: ["running", "paused"],
          next_action_label: "下一步：标记执行中",
          artifact_type: "task_package",
          artifact_path: null,
          recent_audit_events: [
            {
              event_id: "audit:browser-preview:dev:created",
              event_type: "task_draft_created",
              before_state: "missing_task_draft",
              after_state: "draft",
              created_at: "2026-06-19T10:00:00.000Z",
              reason: "浏览器预览示例登记工作项",
            },
          ],
        },
        {
          work_item_id: directorWorkItemId,
          workflow_id: previewWorkflowId,
          title: "规划与回收",
          state: "draft",
          assigned_role_id: "director",
          current_node_id: directorNodeId,
          next_states: ["ready_to_dispatch"],
          next_action_label: "下一步：拆任务包",
          artifact_type: "task_package",
          artifact_path: null,
          recent_audit_events: [],
        },
        {
          work_item_id: reviewWorkItemId,
          workflow_id: previewWorkflowId,
          title: "审查与结论",
          state: "draft",
          assigned_role_id: "review",
          current_node_id: reviewNodeId,
          next_states: ["ready_for_review"],
          next_action_label: "下一步：等待开发线回传",
          artifact_type: "task_package",
          artifact_path: null,
          recent_audit_events: [],
        },
      ],
      director_reviews: [],
      node_session_bindings: [
        {
          binding_id: "binding:browser-preview:codex-dev",
          project_id: previewProjectId,
          workflow_id: previewWorkflowId,
          node_id: devNodeId,
          work_item_id: devWorkItemId,
          agent_type: "codex",
          adapter_id: "codex-local",
          native_thread_id: previewSessionThreadId,
          native_rollout_path: "/browser-preview/rollouts/layout.jsonl",
          session_title: "智能体布局打磨",
          session_updated_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
          rollout_exists: true,
          project_binding_source: "index_inferred",
          binding_source: "workflow_bound",
          binding_mode: "select_existing_session",
          lifecycle: "active",
          created_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
          updated_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
          warnings: [],
        },
      ],
      node_dispatches: [],
      execution_controls: [],
      permission_requests: [],
      execution_attempts: [],
      derived_workflow: previewDerivedWorkflow,
    },
  ],
  project_blackboards: [],
  warnings: ["浏览器预览示例数据；不执行真实读取或派发。"],
};

// 项目咨询方案草案：1 份 pending_user_confirmation 的方案。
// project_id / workflow_id 必须与上面工作流一致，方案卡才会按该工作流过滤命中。
export const browserPreviewProposalStore: ProjectConsultationProposalStoreV1 = {
  schema_version: "project_consultation_proposal_store.v1",
  revision: 1,
  proposals: [
    {
      proposal_id: "proposal:browser-preview:pending",
      schema_version: "project_consultation_proposal.v1",
      project_id: previewProjectId,
      workflow_id: previewWorkflowId,
      title: "桌面壳预览项目咨询方案草案",
      user_goal: "让用户先确认工作流自动推进的方案范围。",
      goal_summary: "确认任务包、角色、读写范围、工具和停止条件后，再进入全局复核。",
      proposed_steps: [
        "整理项目目标和当前任务包。",
        "确认允许角色、agent、读写范围和工具。",
        "用户确认后等待全局主管边界复核。",
      ],
      scope_draft: {
        allowed_role_ids: ["codex-dev", "project_director"],
        allowed_agent_ids: [previewSessionThreadId],
        allowed_read_roots: [previewProjectRoot],
        allowed_write_roots: [`${previewProjectRoot}/src`],
        allowed_tools: ["read_file"],
        allowed_checks: ["npm run typecheck"],
        allowed_task_package_kinds: ["task_package"],
        stop_conditions: ["超出读写范围或需要权限升级时必须停下。"],
        max_worker_dispatches: 3,
        max_runtime_minutes: 60,
      },
      risks: [
        {
          risk_id: "risk:browser-preview:scope",
          severity: "warning",
          summary: "用户确认后仍不能自动派发。",
          mitigation: "等待全局主管复核。",
        },
      ],
      acceptance_criteria: ["确认后授权仍停在待全局复核。"],
      status: "pending_user_confirmation",
      plan_authorization_id: null,
      created_by_role: "project_consultant",
      created_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
      updated_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
    },
  ],
  decisions: [],
  audit_events: [
    {
      audit_event_id: "audit:browser-preview:proposal-created",
      event_type: "project_consultation_proposal_created",
      actor_id: "browser-preview-fixture",
      actor_role: "project_consultant",
      project_id: previewProjectId,
      workflow_id: previewWorkflowId,
      proposal_id: "proposal:browser-preview:pending",
      plan_authorization_id: null,
      before_status: null,
      after_status: "pending_user_confirmation",
      reason: "创建浏览器预览项目咨询方案草案。",
      created_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
    },
  ],
  updated_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
  warnings: [],
};

// 方案授权摘要：1 份 pending_global_boundary_review 的授权（用户已确认、等全局复核），
// 让右侧授权摘要也有内容。source_proposal_id 指向上面的方案。
export const browserPreviewPlanAuthorizationStore: PlanAuthorizationStoreV1 = {
  schema_version: "plan_authorization_store.v1",
  revision: 1,
  authorizations: [
    {
      authorization_id: "plan-auth:browser-preview:pending-global",
      schema_version: "plan_authorization.v1",
      project_id: previewProjectId,
      workflow_id: previewWorkflowId,
      source_proposal_id: "proposal:browser-preview:pending",
      title: "桌面壳预览方案授权",
      goal_summary: "只允许浏览器预览示例范围内的任务包检查。",
      status: "pending_global_boundary_review",
      scope: {
        project_id: previewProjectId,
        workflow_id: previewWorkflowId,
        allowed_role_ids: ["codex-dev"],
        allowed_agent_ids: [previewSessionThreadId],
        allowed_read_roots: [previewProjectRoot],
        allowed_write_roots: [`${previewProjectRoot}/src`],
        allowed_tools: ["read_file"],
        allowed_checks: [],
        allowed_task_package_kinds: ["task_package"],
        max_worker_dispatches: 1,
        max_runtime_minutes: 30,
        stop_conditions: [
          {
            condition_id: "requires-user-confirmation",
            kind: "requires_user_confirmation",
            summary: "需要用户确认时停止。",
            requires_user_confirmation: true,
          },
        ],
      },
      user_confirmation: {
        confirmed_by: "user",
        confirmed_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
        confirmation_summary: "用户确认浏览器预览示例方案授权范围。",
      },
      global_boundary_review: null,
      audit_refs: ["audit:plan-auth:browser-preview:created", "audit:plan-auth:browser-preview:user-confirmed"],
      created_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
      updated_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
      expires_at_ms: null,
    },
  ],
  audit_events: [],
  updated_at_ms: Date.parse("2026-06-19T10:00:00.000Z"),
  warnings: [],
};
